import type { UsCase } from './types';

/** US case bank, part 2 of 2 (US-C-26 .. US-C-50). See ./types.ts. */
export const US_CASES_B: UsCase[] = [
  {
    code: 'US-C-26',
    slug: 'colorado-ski-resort-profits',
    title: "A Colorado ski resort's profits have halved",
    type: 'profitability',
    difficulty: 'medium',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'prof',
    industry: 'Travel & leisure',
    situation:
      "An independent Colorado ski resort saw EBITDA fall from $40M to $20M over two seasons. The owners blame the weather. They want to know if that is the whole story and what to do.",
    facts: [
      'Skier visits fell from 900K to 780K; average lift-ticket yield rose from $90 to $98 per visit.',
      'Revenue fell from $180M to $168M; everything that is not lift tickets (lodging, food, ski school, rentals) scales with visits.',
      'Operating costs rose from $140M to $148M: +$5M for employee housing and +$3M of wages.',
      'The mega-resort season passes now cover several nearby mountains.',
    ],
    asks: [
      'Build the EBITDA bridge from $40M to $20M.',
      'How much is weather, and how much is controllable?',
      'What would you recommend?',
    ],
    hint: 'Split revenue into lift tickets (visits × yield) and everything else (visits × spend per visit), then add the cost increase.',
    solution:
      "Lift tickets went from 900K × $90 = $81M to 780K × $98 ≈ $76.4M (−$4.6M). Other revenue went from $99M to ~$91.6M (−$7.4M) because fewer visitors spent on lodging, food and lessons. Costs rose $8M. That is −$4.6M − $7.4M − $8M = −$20M. Weather explains part of the 13% visit decline, but so do the multi-mountain passes that pull skiers to rivals, and costs are fully controllable. Recommendations: sell season passes early (guaranteed revenue that hedges weather and competes with the mega-passes), invest in snowmaking, build summer revenue (mountain biking, events, weddings) to use fixed costs year-round, price tickets dynamically, and partner with the town on employee housing rather than owning it.",
  },
  {
    code: 'US-C-27',
    slug: 'medicare-advantage-arizona',
    title: 'Should a health insurer enter Medicare Advantage in Arizona?',
    type: 'market entry',
    difficulty: 'hard',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'ent',
    industry: 'Health insurance',
    situation:
      'A Midwestern health insurer sells commercial plans only. Its board wants to enter Medicare Advantage (MA) in Arizona, one of the fastest-growing retirement markets, and targets 30,000 members within three years.',
    facts: [
      'Arizona has about 1.4M Medicare beneficiaries; about 40% are in Medicare Advantage.',
      'Average MA revenue is ~$14,000 per member per year; a mature plan runs an 86% medical loss ratio and 10% admin cost.',
      'Plans rated 4 stars or higher earn a bonus of roughly 5% of revenue.',
      'New plans typically run a ~92% medical loss ratio in their first two years.',
    ],
    asks: [
      'How big is the opportunity and what share does the target imply?',
      'What are the economics of 30,000 members?',
      'How should the insurer enter?',
    ],
    hint: 'Members × revenue per member, then apply the loss ratio and admin to get margin. Don’t forget the star bonus and the early-years penalty.',
    solution:
      "Arizona MA has ~1.4M × 40% = 560K members, so 30K members is ~5.4% share: ambitious for a newcomer but achievable in three years. Revenue at 30K members is ~$420M. A mature plan's margin is 100% − 86% − 10% = 4%, about $17M a year, and reaching 4 stars adds ~5% of revenue (~$21M), more than doubling profit. In the first two years a 92% loss ratio means losses of roughly 2% of revenue. The critical assets are a provider network and care management that controls the loss ratio. Recommendation: enter through a value-based partnership with a large Phoenix–Tucson health system (shared savings, the system's brand and doctors), focus on those two metros, invest in the star-rating drivers (preventive care, member experience), and expect profitability from year three.",
  },
  {
    code: 'US-C-28',
    slug: 'craft-brewery-record-volume',
    title: "A craft brewery's profits fall despite record volume",
    type: 'profitability',
    difficulty: 'easy',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 15,
    cluster: 'prof',
    industry: 'Beverages',
    situation:
      'A Colorado craft brewery grew volume 30% by getting into grocery chains, yet profit dropped by three quarters. The founder is confused.',
    facts: [
      'Volume grew from 50,000 to 65,000 barrels; average net price per barrel fell from $300 to $260.',
      'Production cost is flat at $150 per barrel.',
      'Marketing and slotting fees rose from $2M to $3.5M; other fixed costs are $3M.',
    ],
    asks: [
      'Walk the profit before and after.',
      'Why did growth destroy profit, and what would you do?',
    ],
    hint: 'Gross profit per barrel, before and after, tells most of the story.',
    solution:
      "Before: 50K × $300 = $15M revenue, $7.5M of production cost, $7.5M gross profit, minus $2M of marketing and $3M fixed = $2.5M profit. After: 65K × $260 = $16.9M revenue, $9.75M of cost, $7.15M gross profit, minus $3.5M and $3M = $0.65M. Gross profit per barrel fell from $150 to $110 because the new volume came through low-price grocery channels, and slotting fees rose to buy that shelf space. The brewery bought volume, not profit. Recommendation: measure profitability by channel and by chain, exit the grocery accounts that lose money after slotting, raise prices in the taproom and on-premise accounts where the brand is strongest, and grow grocery only in chains that support a better price.",
  },
  {
    code: 'US-C-29',
    slug: 'private-equity-car-wash-chain',
    title: 'A private equity firm considers buying a chain of express car washes',
    type: 'm&a',
    difficulty: 'medium',
    firm: 'Oliver Wyman',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'ma',
    industry: 'Consumer services',
    situation:
      'A PE firm is looking at 60 express car washes across the Midwest. The seller wants 14x EBITDA, well above what most consumer-services businesses sell for. The partner asks whether it is worth it.',
    facts: [
      'Revenue $90M; EBITDA margin 38% (~$34.2M); asking price ~$479M (14x).',
      '45% of revenue comes from unlimited monthly memberships at about $30 a month.',
      'A new site costs $5M and ramps to $1.6M of revenue at a 40% margin within three years.',
      'The fund would use 60% debt.',
    ],
    asks: [
      'Why might this business deserve a premium multiple?',
      'Build a value creation plan and estimate returns.',
      'What are the risks?',
    ],
    hint: 'Membership revenue behaves like a subscription. Then value new sites: what does $1 of new-site EBITDA cost to build?',
    solution:
      "The premium rests on recurring membership revenue (45% of sales), high margins and cheap growth. Each new site produces ~$640K of EBITDA for $5M, a ~7.8x build multiple, so building sites and owning them at 13–14x creates value. Plan: 5 new sites a year for 5 years (+25 sites, ~$16M of EBITDA, ~$125M of capex funded largely from cash flow), plus ~3% a year organic growth on the base, for exit EBITDA of ~$56M. At a 13x exit, enterprise value is ~$720M. Entry equity is 40% × $479M ≈ $192M; if debt falls from ~$287M to ~$220M, exit equity is ~$500M, about 2.6x and an IRR in the low 20s. Risks: new competitors opening nearby, weather, membership churn, and whether 13x holds at exit. Recommendation: proceed if diligence confirms site-level membership retention and a pipeline of good sites.",
  },
  {
    code: 'US-C-30',
    slug: 'orlando-theme-park-skip-the-line',
    title: 'Pricing a skip-the-line pass at an Orlando theme park',
    type: 'pricing',
    difficulty: 'medium',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'pri',
    industry: 'Travel & leisure',
    situation:
      'A regional theme park near Orlando wants to sell a front-of-line pass. Marketing wants a low price to maximize uptake; operations warns that too many passes will ruin the regular lines.',
    facts: [
      '4M visitors a year; average ticket $110.',
      'Research: 12% of visitors would pay $60, 6% would pay $90 and 3% would pay $130.',
      'To keep regular lines acceptable, no more than 8% of visitors can hold a pass on any day.',
    ],
    asks: [
      'Which price maximizes revenue within the capacity limit?',
      'What is it worth per year?',
      'How would you refine the pricing?',
    ],
    hint: 'Revenue per 100 visitors at each price, but cap the number of passes at 8.',
    solution:
      "Per 100 visitors: at $60, 12 would buy, but only 8 passes can be sold, so revenue is 8 × $60 = $480. At $90: 6 × $90 = $540. At $130: 3 × $130 = $390. $90 wins, and 6% stays within the 8% limit. With 4M visitors that is 40K × $540 ≈ $21.6M a year of almost pure margin. Marketing's low price actually earns less because the capacity cap binds. Refinements: price dynamically ($70 on quiet weekdays, $110–130 on peak days and holidays), sell passes only up to the daily cap, and offer a premium single-ride version for the park's top two coasters.",
  },
  {
    code: 'US-C-31',
    slug: 'ohio-university-enrollment-decline',
    title: "A private university's enrollment keeps falling",
    type: 'growth',
    difficulty: 'medium',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 20,
    cluster: 'ent',
    industry: 'Higher education',
    situation:
      "A private university in Ohio has lost 12% of its undergraduates in five years and faces the Midwest 'demographic cliff' of fewer 18-year-olds. The president asks how to stabilize tuition revenue.",
    facts: [
      '8,000 undergraduates; list tuition $42,000 but the average discount rate is 55%, so net tuition is ~$18,900.',
      'Each freshman class has about 2,000 students; first-year retention is 78% vs 85% at peers.',
      'The number of 18-year-olds in the Midwest is projected to fall about 10% by 2035.',
      'Online degree programs for working adults at peer schools charge about $12,000 a year.',
    ],
    asks: [
      'How big is net tuition revenue today, and what are the levers?',
      'Size each lever.',
      'What would you prioritize?',
    ],
    hint: 'Net tuition = students × (list price × (1 − discount rate)). Look at keeping students, not just recruiting them.',
    solution:
      "Net tuition revenue is 8,000 × $18,900 ≈ $151M. Retention: closing the 7-point gap keeps ~140 more students from each freshman class, ~$2.6M a year per class and ~$8M a year once it flows through all classes. Discount discipline: 3 points less discount on a 2,000-student class is ~$2.5M a year per class, but risks yield. New markets: 1,500 online adult students at $12,000 each add ~$18M a year and are not exposed to the 18-year-old decline. Graduate and certificate programs linked to regional employers add more. Recommendation: fix retention first (advising, early-alert systems, financial aid for continuing students), build a focused online adult program in two or three high-demand fields, and manage the discount rate with better aid modeling.",
  },
  {
    code: 'US-C-32',
    slug: 'michigan-battery-tray-plant',
    title: "A Michigan auto-parts plant can't keep up with EV demand",
    type: 'operations',
    difficulty: 'hard',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'ops',
    industry: 'Automotive manufacturing',
    situation:
      'A supplier makes aluminum battery trays for an electric pickup assembled in Michigan. The automaker needs 1,200 trays a day; the plant ships about 1,000 and pays late-delivery penalties.',
    facts: [
      'Three steps: stamping (1,500 trays a day capacity), welding and painting (1,300 a day).',
      'Welding has 8 robots, each able to weld 150 trays a day if it never stopped; actual availability is 83%.',
      'A new welding robot costs $2.5M; a preventive-maintenance program could lift availability to 95%.',
      'The contract charges $400 per tray short; the plant runs 250 days a year.',
    ],
    asks: [
      'Find the bottleneck.',
      'What is the shortfall costing?',
      'What combination of fixes gets the plant to 1,200 a day?',
    ],
    hint: 'Compute effective capacity at each step. The lowest one is the plant’s output.',
    solution:
      "Welding is the bottleneck: 8 × 150 × 83% ≈ 996 trays a day, matching the ~1,000 shipped, while stamping (1,500) and painting (1,300) have spare capacity. The shortfall of ~200 trays a day costs 200 × 250 × $400 = $20M a year in penalties, plus the relationship risk. Fixes: maintenance alone lifts welding to 8 × 150 × 95% = 1,140; a ninth robot alone gives 9 × 150 × 83% ≈ 1,121; both give ~1,283, above demand with a buffer. Recommendation: start the maintenance program now (cheap and fast), order the ninth robot ($2.5M pays back in about six weeks of avoided penalties), and run weekend welding shifts until the robot is installed.",
  },
  {
    code: 'US-C-33',
    slug: 'hospital-system-supply-costs',
    title: "A hospital system's supply costs are out of line",
    type: 'cost reduction',
    difficulty: 'hard',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 25,
    cluster: 'ops',
    industry: 'Healthcare',
    situation:
      "A 12-hospital system in the Southeast spends far more on supplies than its peers. The CFO wants a credible savings plan that surgeons will accept.",
    facts: [
      'Revenue $6B; supply spend $1.1B (18% of revenue vs about 15% at peers).',
      'Physician preference items (implants, devices) are 40% of supply spend; the system buys knee implants from three vendors.',
      'Commodity items (gloves, gowns, IV sets) are the other 60%.',
      'An estimated 3% of supplies are wasted or expire.',
    ],
    asks: [
      'How big is the gap to peers?',
      'Where would you find savings, and how much?',
      'How do you get physicians on board?',
    ],
    hint: 'Separate physician-preference items from commodities: the levers and the politics are different.',
    solution:
      "The gap to peers is 3 points × $6B ≈ $180M. Physician preference items are ~$440M; standardizing on one or two vendors per category and renegotiating typically saves 10–15%, about $44–66M. Commodities (~$660M): better group-purchasing contracts and fewer SKUs save ~5%, ~$33M. Waste and expiry at 3% is ~$33M, much of which can be recovered with par-level management and consignment. That is roughly $110–130M, with clinical variation (different surgeons using different products for the same procedure) as the next lever. Physician engagement is the key: value-analysis committees led by surgeons, transparent cost and outcome data per surgeon, and gain-sharing that returns part of the savings to departments.",
  },
  {
    code: 'US-C-34',
    slug: 'restaurant-payroll-startup-gtm',
    title: 'A payroll startup wants to win US restaurants',
    type: 'go to market',
    difficulty: 'medium',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'ent',
    industry: 'B2B software',
    situation:
      'A startup sells payroll and tip-management software built for restaurants. It has 2,000 customers from direct sales and must choose how to scale.',
    facts: [
      'Price is $150 a month per location; gross margin 80%; about 25% of customers churn each year.',
      'The US has about 1M restaurant locations; roughly 60% are independents or small chains.',
      'Direct sales cost about $1,200 to acquire a location.',
      'Point-of-sale (POS) partners would resell it for a 20% revenue share, with acquisition cost near $300 per location.',
    ],
    asks: [
      'How big is the addressable market?',
      'Compare direct sales and POS partnerships on customer economics.',
      'What go-to-market would you recommend?',
    ],
    hint: 'Lifetime value = annual gross profit × expected customer lifetime; compare it with acquisition cost for each channel.',
    solution:
      "The addressable market is ~600K independent and small-chain locations × $1,800 a year ≈ $1.1B. Annual gross profit per location is $1,800 × 80% = $1,440, and with 25% churn the average customer stays ~4 years, so lifetime value is ~$5,760. Direct: lifetime value to acquisition cost is ~4.8x, healthy but slow to scale. POS partner: the 20% share costs $360 a year, leaving ~$1,080 of gross profit a year (~$4,320 over the lifetime) against ~$300 of acquisition cost, ~14x, and far faster reach. Recommendation: make POS integrations and reseller partnerships the primary engine, keep a small direct team for multi-unit chains where the account value justifies it, and invest in churn reduction since every point of churn raises lifetime value in both channels.",
  },
  {
    code: 'US-C-35',
    slug: 'mexican-grocer-texas-california',
    title: 'A Mexican grocery chain considers entering Texas and California',
    type: 'market entry',
    difficulty: 'medium',
    firm: 'Deloitte',
    format: 'interviewer-led',
    minutes: 20,
    cluster: 'ent',
    industry: 'Grocery retail',
    situation:
      'A 300-store Mexican grocery chain wants to serve Hispanic households in Texas and California, starting with 20 large-format stores.',
    facts: [
      'Texas and California have about 27M Hispanic residents; average household size is about 3.3.',
      'A Hispanic household spends roughly $8,000 a year on groceries.',
      'A US store would do ~$20M a year at a 4% net margin; building one costs ~$8M.',
      'Strong incumbents include H-E-B, Walmart and several Hispanic specialty grocers.',
    ],
    asks: [
      'How large is the target market?',
      'What do 20 stores imply in share and returns?',
      'Build or buy?',
    ],
    hint: 'Population → households → spend. Then compare the 20-store plan with the market and its payback.',
    solution:
      "About 27M ÷ 3.3 ≈ 8.2M households × $8,000 ≈ $65B of grocery spend. Twenty stores at $20M is $400M, only ~0.6% share, so the market is big enough; the question is whether the client can win profitably. At a 4% margin, 20 stores make ~$16M a year on $160M of capex, a 10-year payback, which is weak. Specialty grocers that win with fresh, prepared foods and cultural authenticity earn 5–6%, and new entrants face years of brand building against H-E-B's loyalty. Recommendation: buy rather than build. Acquire an existing regional Hispanic grocer with real estate and a customer base, then add the client's private-label products, sourcing from Mexico and prepared-food know-how to lift margins.",
  },
  {
    code: 'US-C-36',
    slug: 'steel-mini-mill-margin-collapse',
    title: "A US steel mini-mill's profits collapse as prices fall",
    type: 'profitability',
    difficulty: 'hard',
    firm: 'Kearney',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'prof',
    industry: 'Industrials',
    situation:
      'An electric-arc-furnace steel mill in Indiana saw operating profit fall from about $370M to about $50M in a year. The CEO wants to understand the split between price and volume before deciding whether to chase volume.',
    facts: [
      'Capacity is 2M tons a year; utilization fell from 90% to 72%.',
      'Steel price fell from $1,050 to $850 a ton; scrap (the main input) fell from $450 to $400 a ton, and each ton of steel needs 1.1 tons of scrap.',
      'Other variable conversion costs are $250 a ton; fixed costs are $180M a year.',
    ],
    asks: [
      'Rebuild profit before and after.',
      'Split the decline into spread (price minus scrap cost) and volume.',
      'Should the mill cut prices to win volume back?',
    ],
    hint: 'Metal spread = steel price − 1.1 × scrap price. Profit = volume × (spread − conversion cost) − fixed costs.',
    solution:
      "Before: 1.8M tons; spread $1,050 − 1.1 × $450 = $555; profit 1.8M × ($555 − $250) − $180M ≈ $369M. After: 1.44M tons; spread $850 − $440 = $410; profit 1.44M × $160 − $180M ≈ $50M. Spread effect at today's volume: −$145 × 1.44M ≈ −$209M. Volume effect: −0.36M tons × $305 ≈ −$110M. Together that is the ~$319M decline. Two-thirds is spread, which the mill cannot fix by cutting prices: every $10 of price cut on 1.44M tons costs ~$14M. Recommendation: protect spread (contract pricing, value-added grades such as coated and automotive steel, scrap purchasing discipline), flex costs (idle a shift, shift melting to off-peak power hours), and don't chase volume below full-cost price.",
  },
  {
    code: 'US-C-37',
    slug: 'pharmacy-chain-online-threat',
    title: 'A regional pharmacy chain responds to online pharmacies',
    type: 'competitive strategy',
    difficulty: 'medium',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'soft',
    industry: 'Retail pharmacy',
    situation:
      "A 400-store pharmacy chain in the Southeast is watching online pharmacies and mail order take prescriptions. The CEO asks how much is at risk and how to compete.",
    facts: [
      'Revenue $3.2B; pharmacy is 65% of revenue at a 20% gross margin; front-of-store retail earns 28%.',
      'Maintenance medications (easiest to move online) are 18% of pharmacy revenue.',
      'Mail-order and online already fill about 12% of US prescriptions, and the share is rising.',
    ],
    asks: [
      'How much revenue and profit is at risk over five years?',
      'Where can a local chain win?',
      'What would you recommend?',
    ],
    hint: 'Start with the prescriptions most likely to move online, then remember the knock-on effect on store visits.',
    solution:
      "Pharmacy revenue is ~$2.08B; maintenance medications are ~$375M. If online takes a third of that over five years, the chain loses ~$125M of revenue and ~$25M of gross profit, plus front-store purchases from lost trips (at 28% margin). The chain cannot beat online on price for routine refills; it can win on what online cannot do: clinical services (vaccinations, tests, chronic-care support), same-day and delivery options, human advice, and partnerships with local health plans and doctors. Recommendation: match on convenience (90-day fills, home delivery, an app), differentiate on care services that bring people into stores, and consolidate low-volume stores to fund both.",
  },
  {
    code: 'US-C-38',
    slug: 'outdoor-apparel-growth-slowdown',
    title: "A premium outdoor-apparel brand's growth is slowing",
    type: 'growth',
    difficulty: 'hard',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'ent',
    industry: 'Apparel',
    situation:
      "A premium outdoor-apparel brand grew fast for a decade but is now flat at $1.2B. Warm winters hurt its core outerwear. The CEO asks for a growth plan that is less exposed to the weather.",
    facts: [
      'Channels: wholesale 55%, direct-to-consumer e-commerce 30%, own stores 15%.',
      'Direct-to-consumer gross margin is 65% vs 45% for wholesale.',
      '60% of revenue is outerwear; only 28% of customers buy again within a year.',
    ],
    asks: [
      'What are the growth levers?',
      'Size the channel-mix lever.',
      'What plan would you recommend?',
    ],
    hint: 'Think margin as well as revenue: moving sales between channels can grow profit without growing sales.',
    solution:
      "Channel mix: shifting 10 points of revenue (~$120M) from wholesale to direct adds ~20 points of margin on that revenue, ~$24M of gross profit with no new sales. Repeat purchase: lifting repurchase from 28% toward 33% through loyalty, a resale and repair program, and personalized drops grows the direct channel. Category: base layers, footwear and year-round lifestyle products reduce the 60% dependence on winter outerwear. Geography: stores in affluent Sun Belt metros where the brand is under-penetrated. Recommendation: a three-part plan of direct-channel shift and loyalty, year-round categories and selective stores, while trimming weaker wholesale accounts that discount the brand.",
  },
  {
    code: 'US-C-39',
    slug: 'airline-basic-economy-fare',
    title: 'Should an airline add basic economy on New York–Miami?',
    type: 'pricing',
    difficulty: 'hard',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 25,
    cluster: 'pri',
    industry: 'Airlines',
    situation:
      'An airline flies 20 daily New York–Miami flights at a single main-cabin fare. It is considering a cheaper basic-economy fare without seat selection or a carry-on bag.',
    facts: [
      '180 seats per flight; load factor 85%; main-cabin fare $220.',
      'Proposed basic-economy fare: $180.',
      'Expected: 20% of current passengers buy down; 60% of basic-economy buyers pay ~$35 in bag or seat fees; the load factor rises 5 points.',
    ],
    asks: [
      'What is the daily revenue impact?',
      'Should the airline launch it?',
    ],
    hint: 'Three effects: buy-down loss, fees from buy-downers, and revenue from new passengers.',
    solution:
      "Seats a day: 20 × 180 = 3,600; passengers at 85% = 3,060. Buy-down: 20% = 612 passengers × −$40 ≈ −$24.5K a day. Fees from them: 60% × 612 × $35 ≈ +$12.9K. New passengers: 5 points × 3,600 = 180 × ($180 + 60% × $35 = $201) ≈ +$36.2K. Net ≈ +$24.6K a day, about $9M a year for this route. Recommendation: launch, but design the fare fences carefully (no seat selection, last boarding group, no changes) so the buy-down rate stays near 20%; if it reaches ~35%, most of the gain disappears.",
  },
  {
    code: 'US-C-40',
    slug: 'regional-bank-merger',
    title: 'Should a regional bank merge with its neighbor?',
    type: 'm&a',
    difficulty: 'hard',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'ma',
    industry: 'Banking',
    situation:
      'Bank A ($30B of assets) is considering buying Bank B ($18B), whose branches overlap heavily with its own in two states. B’s shareholders expect a 25% premium.',
    facts: [
      "Bank B: revenue $720M, efficiency ratio (non-interest expense ÷ revenue) 68%, 300 branches, market value $2.4B.",
      '40% of B’s branches are within a mile of an A branch.',
      "In-market bank deals typically cut 25–30% of the target's non-interest expense; the corporate tax rate is 21%.",
      'Bank stocks trade at about 11x earnings.',
    ],
    asks: [
      'What are the cost synergies worth?',
      'Does that justify the premium?',
      'What are the main risks?',
    ],
    hint: 'Expense base × savings rate, after tax, capitalized at the earnings multiple; compare with the premium paid.',
    solution:
      "B's non-interest expense is 68% × $720M ≈ $490M. Savings of 25–30% are $122–147M pre-tax, ~$97–116M after tax, worth ~$1.07–1.28B at 11x earnings. The premium is 25% × $2.4B = $600M, so the deal creates value even at the low end. Branches: of the ~120 overlapping, closing ~80 at ~$1.2M of cost each delivers ~$96M, most of the savings. Risks: deposit runoff when branches close (budget 3–5% of B's deposits), regulatory approval, and merging two core banking systems. Recommendation: proceed, with a disciplined branch and systems integration plan and retention offers for B's most valuable depositors.",
  },
  {
    code: 'US-C-41',
    slug: 'saas-gross-margin-sliding',
    title: "A SaaS company's gross margin is sliding",
    type: 'profitability',
    difficulty: 'medium',
    firm: 'Deloitte',
    format: 'interviewer-led',
    minutes: 20,
    cluster: 'prof',
    industry: 'B2B software',
    situation:
      "A US marketing-software company with $150M of annual recurring revenue saw gross margin fall from 78% to 69% in two years. Investors are asking why.",
    facts: [
      'Cloud hosting rose from 10% to 15% of revenue after the launch of AI features.',
      'Customer support rose from 8% to 11% of revenue.',
      'Implementation services are 10% of revenue and run at a small loss.',
    ],
    asks: [
      'Explain the 9-point decline in dollars.',
      'How would you get back to 75% or better?',
    ],
    hint: 'Each point of gross margin is $1.5M here. Attribute the nine points to cost lines.',
    solution:
      "Nine points on $150M is ~$13.5M: hosting +5 points (~$7.5M), support +3 points (~$4.5M), and the remaining ~1 point (~$1.5M) from a larger share of loss-making implementation work. Fixes: price the AI features on usage so heavy users pay for the compute they consume; cut inference cost (smaller models for simple tasks, caching, reserved capacity); deflect support with in-product help and a knowledge base; and price implementation at cost-plus or hand it to partners. Recommendation: usage pricing plus cost engineering can recover ~4 points, and support and services ~2 more, getting back to ~75% within a year.",
  },
  {
    code: 'US-C-42',
    slug: 'gym-chain-pilates-studios',
    title: 'Should a gym chain launch boutique Pilates studios?',
    type: 'market entry',
    difficulty: 'easy',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 15,
    cluster: 'ent',
    industry: 'Fitness',
    situation:
      'A national gym chain sees members leaving for boutique Pilates studios. It is considering opening its own reformer Pilates studios next to existing gyms.',
    facts: [
      'A studio has 12 reformer machines and runs 8 classes a day, every day.',
      'Average price per class (after package discounts) is $32; expected fill rate is 75%.',
      'Rent and staff cost about $55K a month; build-out costs $450K.',
    ],
    asks: [
      'What are the economics of one studio?',
      'What fill rate breaks even?',
      'Would you launch?',
    ],
    hint: 'Monthly revenue = classes × seats × fill rate × price.',
    solution:
      "A studio runs ~240 classes a month; at 75% of 12 seats that is ~2,160 visits × $32 ≈ $69K a month. Minus $55K of costs leaves ~$14K a month, ~$169K a year, so the $450K build pays back in ~2.7 years. Break-even fill is $55K ÷ (240 × 12 × $32) ≈ 60%, which leaves some cushion. The chain has two advantages over independents: an existing member base to cross-sell and cheap space next to its gyms. Recommendation: pilot five studios in affluent suburbs next to the best-performing gyms, bundle a Pilates add-on into memberships, and scale if fill rates stay above ~70% after six months.",
  },
  {
    code: 'US-C-43',
    slug: 'online-apparel-shipping-costs',
    title: "An online apparel retailer's shipping costs are out of control",
    type: 'cost reduction',
    difficulty: 'easy',
    firm: 'Accenture Strategy',
    format: 'interviewer-led',
    minutes: 15,
    cluster: 'ops',
    industry: 'E-commerce',
    situation:
      'A US online apparel retailer offers free shipping over $50 and free returns. Shipping now eats most of its margin. The CFO wants ~$9M of savings without hurting sales.',
    facts: [
      '4M orders a year; average order value $62; average outbound shipping cost $9.50 per package.',
      '30% of orders ship in two packages because items sit in different warehouses; each extra package costs about $6.',
      '25% of orders are returned; return shipping costs $7.',
      'Research suggests that at a $75 free-shipping threshold, 15% of orders would pay a $6.95 shipping fee.',
    ],
    asks: [
      'Where is the money going?',
      'How would you find ~$9M?',
    ],
    hint: 'Break shipping into outbound, split shipments and returns, then attach a lever to each.',
    solution:
      "Outbound is ~4M × $9.50 = $38M; split shipments add 1.2M extra packages × $6 = ~$7.2M; returns cost 1M × $7 = ~$7M. Levers: rebalance inventory so fewer orders split (halving splits saves ~$3.6M); raise the free-shipping threshold to $75 (600K orders paying $6.95 is ~$4.2M, and many customers will add items instead, raising order value); cut returns 20% with better size guides and fit tools (~$1.4M). That is ~$9.2M. A small return fee for non-loyalty members is a further option, but test it carefully against conversion.",
  },
  {
    code: 'US-C-44',
    slug: 'cardiac-monitor-launch',
    title: 'Launching a wearable heart monitor to US cardiologists',
    type: 'go to market',
    difficulty: 'hard',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 25,
    cluster: 'ent',
    industry: 'Medical devices',
    situation:
      'A startup has FDA clearance for a wearable patch that monitors heart rhythm for 14 days. It must decide how to launch with limited capital.',
    facts: [
      'Medicare reimburses about $300 per 14-day monitoring episode; the US has about 5M such episodes a year.',
      'The device and data review cost ~$60 per episode.',
      'A cardiology practice that adopts orders about 20 episodes a month.',
      'A sales rep costs $250K a year fully loaded and can cover about 40 practices.',
    ],
    asks: [
      'How big is the market?',
      'What are the economics per practice and per rep?',
      'How would you launch?',
    ],
    hint: 'Gross profit per episode × episodes per practice per year, then scale up to what one rep covers.',
    solution:
      "The market is ~5M × $300 ≈ $1.5B a year. Each adopting practice generates 240 episodes a year × $240 of gross profit ≈ $58K; one rep covering 40 practices produces ~$2.3M of gross profit for $250K of cost, excellent economics once adoption happens. A 100-rep force covering 4,000 practices would reach ~960K episodes (~19% share, ~$230M of gross profit). The real constraints are adoption (clinical evidence, workflow integration, reimbursement support) and cash. Recommendation: launch with ~25 reps in a few dense regions (e.g., Texas and the Southeast), target large cardiology groups and health systems first, publish diagnostic-yield evidence, use distributors for small practices, and scale reps as adoption per practice proves out.",
  },
  {
    code: 'US-C-45',
    slug: 'rideshare-robotaxi-phoenix',
    title: 'A ride-hailing company faces robotaxis in Phoenix',
    type: 'competitive strategy',
    difficulty: 'hard',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'soft',
    industry: 'Mobility',
    situation:
      "A driverless-taxi operator is scaling in Phoenix at lower prices. The market-leading ride-hailing app wants to know how much it could lose and whether to fight on price.",
    facts: [
      'Phoenix has about 60,000 ride-hail trips a day; the client has 70% share; the average fare is $22.',
      'Drivers receive 70% of the fare, so the client keeps 30%.',
      'The robotaxi operator prices 15% lower and plans 1,000 vehicles doing ~20 trips a day each within two years.',
    ],
    asks: [
      'How much could the client lose?',
      'Evaluate a price war versus a partnership.',
      'What would you recommend?',
    ],
    hint: 'Robotaxi capacity → trips taken from the client → the client’s take per trip.',
    solution:
      "Robotaxi capacity is 1,000 × 20 = 20K trips a day, a third of the market. If half comes from the client, it loses ~10K trips a day × $6.60 of take (30% of $22) ≈ $66K a day, about $24M a year of contribution. Matching the 15% price cut across all 42K daily trips would cost ~$3.30 per trip, ~$139K a day or ~$50M a year if the company absorbs it, twice the loss it is meant to prevent, and drivers would resist cutting their share. Better: partner with the robotaxi operator to dispatch its vehicles on the client's app for a fee (keeping customers and demand data), compete on reliability, airport access and premium options, and build partnerships with several autonomous-vehicle companies for the longer term.",
  },
  {
    code: 'US-C-46',
    slug: 'cinema-chain-profit-per-screen',
    title: "A cinema chain's profits keep falling",
    type: 'profitability',
    difficulty: 'medium',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'prof',
    industry: 'Media & entertainment',
    situation:
      "A US cinema chain with 150 theaters has gone from a solid profit to a loss. Ticket prices are up, but fewer people come. The CEO wants a bridge and a plan.",
    facts: [
      'Attendance fell from 60M to 42M; the average ticket rose from $11.00 to $12.50.',
      'Concessions average $7.50 per visitor at a 70% margin.',
      'Film rental costs 52% of box office; fixed costs are about $520M a year.',
    ],
    asks: [
      'Rebuild profit before and after.',
      'How much is attendance, and how much is price?',
      'What would you do?',
    ],
    hint: 'Each visitor brings net box office (48% of the ticket) plus concession margin.',
    solution:
      "Before: box office $660M, concessions $450M, film rental $343M, concession cost $135M, fixed $520M, for ~$112M of profit. After: box office $525M, concessions $315M, rental $273M, concession cost $94.5M, fixed $520M, for about −$47M. Each lost visitor costs ~$5.28 of net box office (48% × $11) plus ~$5.25 of concession margin, ~$10.50; 18M fewer visitors ≈ −$190M. The $1.50 price increase adds ~$30M (42M × $1.50 × 48%). Net ≈ −$160M. Recommendation: raise spend per visitor (premium large-format screens, recliners, expanded food and drink), fill weekday seats with dynamic pricing and a subscription, add events (concerts, sports, anime), and close the weakest ~20% of theaters to cut fixed costs.",
  },
  {
    code: 'US-C-47',
    slug: 'solar-installer-home-batteries',
    title: 'Should a California solar installer push into home batteries?',
    type: 'market entry',
    difficulty: 'hard',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 25,
    cluster: 'ent',
    industry: 'Energy',
    situation:
      'California cut how much homeowners are credited for exporting solar power to the grid, which makes storing it in a home battery more valuable. A residential solar installer asks whether to make batteries a core business.',
    facts: [
      'The installer does 15,000 solar installs a year in California; 20% include a battery today.',
      'A battery system sells for $14,000 installed at a 22% gross margin; the federal tax credit covers 30% for the homeowner.',
      'With the new rules, a battery saves a typical homeowner about $1,000 a year, and utility virtual-power-plant programs pay about $500 a year more.',
      'About 1.5M California homes already have solar; roughly 3% a year might add a battery.',
    ],
    asks: [
      'Is the battery a good deal for homeowners?',
      'What is the opportunity for the installer?',
      'What would you recommend?',
    ],
    hint: 'Homeowner payback first (net price ÷ annual value), then new-install attach plus retrofits for the installer.',
    solution:
      "For a homeowner, the net cost after the 30% credit is ~$9,800; with ~$1,500 a year of savings and program payments, payback is ~6.5 years, plus backup power during outages. For the installer: lifting attach from 20% to 60% on 15K installs means 9K batteries, ~$126M of revenue and ~$28M of gross profit vs ~$9M today. Retrofits: 1.5M solar homes × 3% ≈ 45K a year; a 10% share is 4.5K batteries, ~$14M more gross profit. Recommendation: make batteries the default offer (solar plus storage bundled, with financing), enroll customers in utility programs to raise their savings, and build a retrofit campaign aimed at the installer's own past customers first.",
  },
  {
    code: 'US-C-48',
    slug: 'texas-car-dealer-profits',
    title: "A Texas car-dealership group's profits dropped by half",
    type: 'profitability',
    difficulty: 'easy',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 15,
    cluster: 'prof',
    industry: 'Automotive retail',
    situation:
      'A 12-store dealership group in Texas had record profits when car supply was tight. Now that inventory has returned, profits have fallen by half. The owner asks what to do.',
    facts: [
      'The group sells 24,000 new cars a year; gross profit per new car fell from $4,800 to $2,300.',
      'It sells 20,000 used cars a year at ~$2,000 of gross profit each.',
      'Finance and insurance earns ~$1,800 of gross profit per vehicle sold; service and parts earn $150M a year (stable).',
      'Selling, general and administrative costs are $260M a year.',
    ],
    asks: [
      'Rebuild profit before and after.',
      'Where should the group focus?',
    ],
    hint: 'Add up gross profit by department, then subtract SG&A.',
    solution:
      "Before: new $115.2M + used $40M + finance and insurance $79.2M (44K vehicles × $1,800) + service $150M = $384.4M of gross profit, minus $260M = ~$124M. After: new falls to $55.2M, so gross profit is ~$324M and profit ~$64M. The entire $60M drop is new-car margin returning to normal, which the group cannot control. Focus on what it can: service and parts (add bays and technicians, extend hours; this business is stable and high-margin), used cars (buy more vehicles directly from consumers), finance and insurance penetration, and advertising cost per car sold. Recommendation: grow service capacity and used-car volume, and cut SG&A to match the new normal.",
  },
  {
    code: 'US-C-49',
    slug: 'fresh-dog-food-subscription',
    title: 'A fresh dog-food subscription brand wants to keep growing',
    type: 'growth',
    difficulty: 'easy',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 15,
    cluster: 'ent',
    industry: 'Consumer goods',
    situation:
      'A direct-to-consumer fresh dog-food brand has reached ~$80M of revenue, but acquiring customers online keeps getting more expensive. The founders want to know how to keep growing.',
    facts: [
      '100,000 subscribers paying about $67 a month; gross margin 45%.',
      'Customer acquisition cost rose from $150 to $260 in two years.',
      'Monthly churn is 5%.',
      'Pet-specialty and grocery chains are interested, but retailers keep about 40% of the shelf price.',
    ],
    asks: [
      'What is a customer worth, and how has that changed relative to acquisition cost?',
      'What growth options exist?',
      'What would you do first?',
    ],
    hint: 'Lifetime value = monthly gross profit × average lifetime (1 ÷ monthly churn).',
    solution:
      "Monthly gross profit per subscriber is ~$67 × 45% ≈ $30; with 5% monthly churn the average lifetime is 20 months, so lifetime value is ~$600. That was ~4x acquisition cost at $150 and is only ~2.3x at $260. Cutting churn to 4% extends lifetime to 25 months and lifts value to ~$750, the cheapest growth available. Referral programs and bundles (treats, supplements) raise value per customer. Retail reaches customers with no acquisition cost but gives up ~40% of the price, so test it in a few hundred pet-specialty stores with a smaller trial pack. Recommendation: fix churn first, then pilot retail as a second acquisition channel rather than a replacement.",
  },
  {
    code: 'US-C-50',
    slug: 'wisconsin-cheese-company-offer',
    title: 'A family-owned Wisconsin cheese company gets a buyout offer',
    type: 'm&a',
    difficulty: 'medium',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 20,
    cluster: 'ma',
    industry: 'Food manufacturing',
    situation:
      'A third-generation cheese maker has received a $540M offer from a large food company. Some family members want to sell; others want to invest in a new specialty-cheese plant. They ask you to compare the options.',
    facts: [
      'Revenue $500M; EBITDA $45M (9%), growing ~3% a year; the offer is $540M (12x EBITDA).',
      'A $60M specialty plant would add ~$150M of revenue at an 18% EBITDA margin by year five.',
      'Three retiring family members need about $100M of liquidity; the family would take ~$25M a year of dividends if it keeps the business.',
      'Use a 10% discount rate and a 10x exit multiple.',
    ],
    asks: [
      'What is keeping the business worth today?',
      'How does that compare with the offer?',
      'What would you recommend?',
    ],
    hint: 'Project year-5 EBITDA with the new plant, value it at 10x, discount it back, and add the dividends; then subtract the plant cost.',
    solution:
      "Year-5 EBITDA if they keep it: $45M × 1.03^5 ≈ $52M, plus ~$27M from the plant, ~$79M. At 10x that is ~$790M in year five, ~$490M today at 10%. Subtract the plant (~$55M present value) and add dividends (~$25M a year for five years, ~$95M present value): keeping is worth ~$530M, about the same as the offer. So the offer is fair, and the choice turns on execution risk (building a plant and a specialty brand) and the family's liquidity needs. Recommendation: negotiate toward 13x (~$585M), or consider a middle path: sell a minority stake to a private equity partner to fund the retiring members and the plant while the family keeps control.",
  },
];
