import type { UsCase } from './types';

/** US case bank, part 1 of 2 (US-C-01 .. US-C-25). See ./types.ts. */
export const US_CASES_A: UsCase[] = [
  {
    code: 'US-C-01',
    slug: 'midwest-grocery-margins',
    title: "A Midwest grocery chain's margins have nearly halved",
    type: 'profitability',
    difficulty: 'medium',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 20,
    cluster: 'prof',
    industry: 'Grocery retail',
    situation:
      "Heartland Fresh is a regional supermarket chain whose EBITDA margin has fallen from 5.8% to 3.1% in two years while sales stayed flat. The CEO wants to know what happened and what to fix first.",
    facts: [
      '180 stores across Ohio, Indiana and Michigan; revenue $6.3B, flat for two years.',
      'Store labor rose from 12.0% to 13.7% of sales after wage increases.',
      'Shrink (theft, spoilage, damage) rose from 1.8% to 2.6% of sales.',
      'Private label fell from 22% to 18% of sales; private label earns a gross margin 10 points higher than national brands.',
    ],
    asks: [
      'What drove the 2.7-point margin decline? Put a dollar figure on each driver.',
      'Which driver is most fixable within 12 months, and why?',
      'What would you tell the CEO to do?',
    ],
    hint: 'Profit = revenue − costs. With revenue flat, walk each cost line and convert every point of margin into dollars.',
    solution:
      "The decline is 2.7 points on $6.3B, about $170M of EBITDA. Labor added 1.7 points (~$107M), shrink 0.8 points (~$50M), and the private-label mix shift cost 4 points of sales × 10 points of margin = 0.4 points (~$25M). Together that is 2.9 points (~$183M); roughly 0.2 points were offset by better vendor terms. Wages are structural, so attack labor productivity (schedule to traffic, self-checkout in high-volume stores, fewer shelf resets) rather than pay. Shrink is the fastest win: better fresh-food forecasting and loss prevention in the worst 20% of stores can claw back ~0.4 points (~$25M) in a year. Rebuilding private label (price gaps, shelf placement, packaging) recovers another ~0.4 points. Recommendation: a 12-month plan targeting ~1.5 points (≈$95M): labor productivity 0.7, shrink 0.4, private label 0.4.",
  },
  {
    code: 'US-C-02',
    slug: 'canadian-coffee-chain-northeast',
    title: 'A Canadian coffee chain eyes the US Northeast',
    type: 'market entry',
    difficulty: 'medium',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'ent',
    industry: 'Restaurants',
    situation:
      "Maple & Bean, a 400-store Canadian coffee chain, wants to open 60 US stores over three years in Boston, New York and Philadelphia. The board asks whether the Northeast is worth it and how to win against entrenched players.",
    facts: [
      'A mature US store should make $1.4M in annual revenue at a 16% four-wall margin.',
      'Build-out costs $900K per store; new stores take 18 months to reach maturity.',
      "Starbucks and Dunkin' together hold roughly 60% of US coffee-shop sales.",
    ],
    asks: [
      'Is the Northeast an attractive market?',
      'What payback does the store plan imply, and what does 60 stores require?',
      'How could Maple & Bean win? Give a go/no-go.',
    ],
    hint: 'Start with single-store economics (profit per store, payback), then scale to the plan, then ask how they can take share.',
    solution:
      "A mature store makes $1.4M × 16% = $224K of four-wall profit, so payback is $900K / $224K ≈ 4.0 years from maturity, about 5.5 years from opening given the 18-month ramp. Sixty stores need ~$54M of capex and deliver ~$13.4M a year at maturity, before US overhead of perhaps $4–5M. The market is attractive (density, commuter traffic, premium willingness to pay) but convenience is owned by incumbents, so a me-too café loses. Win on a differentiated wedge: a stronger breakfast menu, drive-thru formats in the suburbs, and tight store clustering so brand awareness and supply-chain density build together. Recommendation: stage the entry with 10 stores in Greater Boston and a go/no-go gate at month 18 (revenue per store at or above $1.2M) before scaling to 60.",
  },
  {
    code: 'US-C-03',
    slug: 'private-equity-hvac-rollup',
    title: 'A private equity fund weighs a Sun Belt HVAC roll-up',
    type: 'm&a',
    difficulty: 'hard',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'ma',
    industry: 'Home services',
    situation:
      'A mid-market private equity fund is looking at a residential HVAC service and replacement business with 14 branches in Texas, Florida and Arizona. The seller wants 11x EBITDA. The partner asks whether that price can make the fund its target 20% IRR over five years.',
    facts: [
      'Revenue $220M, EBITDA $26M; asking price 11x EBITDA ($286M).',
      'The fund can finance 55% of the price with debt.',
      'Small local HVAC shops sell for 5–6x EBITDA.',
      'About 40% of revenue comes from recurring maintenance plans; cost of goods is 60% of revenue.',
    ],
    asks: [
      'Is 11x justified for this business?',
      'Build a five-year value creation plan.',
      'What returns could the fund expect, and what are the biggest risks?',
    ],
    hint: 'Returns come from EBITDA growth, multiple arbitrage and debt paydown. Size each one.',
    solution:
      "Paying 11x in an industry that trades at 5–6x only works through growth and multiple arbitrage. Plan: ~6% organic growth a year, ~$8M of EBITDA added through bolt-ons bought at ~6x (~$48M), and ~$2.6M from procurement (2% of ~$132M of COGS). That gets exit EBITDA to ~$40M. At a 10x exit (allowing some compression), enterprise value is ~$400M. Entry equity is 45% × $286M ≈ $129M against ~$157M of debt; if cash flow pays debt down to ~$90M, exit equity is ~$310M, a 2.4x multiple and ~19% IRR, just under target. Risks: technician shortages, replacement demand tied to housing, bolt-on integration, and the exit multiple itself. Recommendation: proceed only if diligence confirms a pipeline of bolt-ons at 6x or less and a path to recurring revenue above 50%, which supports holding an 11x exit; otherwise negotiate toward 10x.",
  },
  {
    code: 'US-C-04',
    slug: 'streaming-ad-tier-pricing',
    title: 'Should a streaming service launch a cheaper ad-supported tier?',
    type: 'pricing',
    difficulty: 'medium',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'pri',
    industry: 'Media & streaming',
    situation:
      'StreamLine, a US video streaming service, is ad-free today. Management wants to add an ad-supported tier at a lower price to grow subscribers, but worries existing members will trade down.',
    facts: [
      '30 million US subscribers at $15.99 a month, no ads.',
      'Proposed ad tier: $7.99 a month; expected ad revenue is $5 per ad-tier subscriber per month.',
      'Research: the ad tier would attract 4 million new subscribers, and 15% of existing subscribers would trade down.',
    ],
    asks: [
      'Does the ad tier grow monthly revenue? By how much?',
      'At what trade-down rate would it break even?',
      'What price would you recommend?',
    ],
    hint: 'Compare revenue per subscriber on each tier (price + ads), then net the new-subscriber gain against the trade-down loss.',
    solution:
      "Ad-tier revenue per subscriber is $7.99 + $5 = $12.99, so each trade-down loses $3.00 a month. Trade-downs: 15% × 30M = 4.5M × $3 = $13.5M a month lost. New subscribers: 4M × $12.99 ≈ $52.0M a month gained. Net ≈ +$38.5M a month, about $460M a year. Break-even needs 52.0 / 3 ≈ 17.3M trade-downs, about 58% of the base, so the decision is robust. On price: if volumes held at $8.99, each extra dollar would add ~$8.5M a month (4M new subscribers plus 4.5M trade-downers paying $1 more), so test $8.99 before locking $7.99. Recommendation: launch the ad tier, test $8.99, and watch ad load and churn closely in the first two quarters.",
  },
  {
    code: 'US-C-05',
    slug: 'texas-gym-chain-double-revenue',
    title: 'A Texas gym chain wants to double revenue in five years',
    type: 'growth',
    difficulty: 'easy',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 15,
    cluster: 'ent',
    industry: 'Fitness',
    situation:
      'LoneStar Fitness runs 45 mid-priced gyms across Texas and wants to double revenue in five years. The founder asks where the growth should come from.',
    facts: [
      'Revenue $90M, about $2M per gym.',
      'Each gym has ~3,000 members paying $50 a month on average, plus ~$200K of personal training and retail.',
      'Member churn is 40% a year.',
      'A new gym costs $3M and reaches 3,000 members in about two years.',
    ],
    asks: [
      'Lay out the ways the chain could grow.',
      'Size each lever.',
      'What would you prioritize?',
    ],
    hint: 'Revenue = gyms × members × price + ancillary. Remember that members in steady state = new sign-ups ÷ churn rate.',
    solution:
      "Doubling means +$90M. Membership revenue is about 45 × 3,000 × $50 × 12 ≈ $81M. Churn: steady-state members equal sign-ups divided by churn, so cutting churn from 40% to 30% raises membership by a third, about +$27M if sign-ups hold. Price: +$5 a month is +10%, about +$8M. Ancillary: lifting personal training and retail from $200K to $400K per gym adds about +$9M. That is ~$44M from the existing base. The remaining ~$46M needs about 23 new gyms at ~$2M each (~$69M of capex). Recommendation: attack churn first (onboarding, class programming, annual plans), then price and ancillary, and fund 20–25 new gyms in fast-growing Austin, Dallas–Fort Worth and San Antonio suburbs.",
  },
  {
    code: 'US-C-06',
    slug: 'nj-warehouse-missed-cutoffs',
    title: 'An e-commerce warehouse keeps missing same-day cutoffs',
    type: 'operations',
    difficulty: 'medium',
    firm: 'Kearney',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'ops',
    industry: 'E-commerce logistics',
    situation:
      "A New Jersey fulfillment center that serves the New York metro area misses the carrier cutoff on almost one order in five. The COO wants to know why, what it costs, and how to fix it before peak season.",
    facts: [
      'The site ships 60,000 orders a day; 18% miss the carrier cutoff.',
      'Pickers average 90 units an hour; an average order has 2.5 units.',
      '70% of orders arrive between noon and 6 p.m.; about 160 pickers are on the floor in that window.',
      'Each late order costs about $4 in expedited shipping or customer credits.',
    ],
    asks: [
      'How big is the problem in dollars?',
      'Where is the bottleneck? Prove it with numbers.',
      'What would you change?',
    ],
    hint: 'Compare the afternoon workload (units per hour) with afternoon picking capacity.',
    solution:
      "Late orders: 18% × 60K = 10.8K a day × $4 ≈ $43K a day, about $16M a year. Afternoon workload: 70% × 60K = 42K orders × 2.5 = 105K units in six hours, or 17.5K units an hour. Capacity: 160 pickers × 90 = 14.4K units an hour. The shortfall of ~3.1K units an hour over six hours is ~18.6K units, about 7.4K orders, which explains most of the 10.8K late orders; packing and trailer loading likely explain the rest. Fixes: add a noon–9 p.m. shift so labor follows the order curve (≈35 more pickers in the peak), move to zone picking to push productivity toward 105 units an hour, prioritize orders by promised ship time, and negotiate a later carrier pickup. Recommendation: reshape shifts first (fastest, cheapest), then process changes.",
  },
  {
    code: 'US-C-07',
    slug: 'national-bank-digital-brand',
    title: 'A national bank considers a digital-only brand for Gen Z',
    type: 'market entry',
    difficulty: 'hard',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 25,
    cluster: 'ent',
    industry: 'Banking',
    situation:
      "A top-10 US bank is losing young customers to digital-only banks. The CEO is considering a separate app-only brand aimed at Americans aged 18 to 27 and wants a view on the economics and the odds of success.",
    facts: [
      'About 70M Americans are aged 18–27; roughly 20% bank primarily with a digital-only bank.',
      'Expected customer economics: $120 a year of revenue, $30 a year of servicing cost, $150 to acquire.',
      'Building the platform costs $250M over three years, and running it about $60M a year.',
      "The bank's target is 3M customers by year five.",
    ],
    asks: [
      'What are the unit economics and payback per customer?',
      'Is 3M customers realistic?',
      'Should the bank do it, and how?',
    ],
    hint: 'Unit economics first (contribution per customer vs acquisition cost), then total investment vs profit at scale, then market share needed.',
    solution:
      "Contribution per customer is $120 − $30 = $90 a year, so acquisition cost pays back in ~1.7 years. At 3M customers that is ~$270M a year of contribution, ~$210M after $60M of run costs. Total investment is ~$250M to build plus 3M × $150 = $450M to acquire, about $700M, so the program pays back around years four to five of scale. On feasibility: 70M × 20% ≈ 14M young adults are already digital-first; 3M means ~4% of the cohort or ~21% of today's digital-primary pool, which is ambitious against established fintechs. Winning needs a hook (early wage access, no-fee overdraft, credit building) and cross-sell into cards and loans that lifts revenue toward $200 a customer. Recommendation: launch lean (buy the core platform rather than build), target 1M customers in three years, and release further spend only if acquisition cost stays at or below $150 and 12-month retention stays at or above 70%.",
  },
  {
    code: 'US-C-08',
    slug: 'southeast-casual-dining-loss',
    title: 'Why is a Southeast restaurant chain suddenly losing money?',
    type: 'profitability',
    difficulty: 'easy',
    firm: 'Deloitte',
    format: 'interviewer-led',
    minutes: 15,
    cluster: 'prof',
    industry: 'Restaurants',
    situation:
      'A family-owned casual-dining chain with 22 restaurants in Georgia and the Carolinas went from a healthy profit to a loss in two years. The owners want to understand why.',
    facts: [
      'Revenue fell from $66M to $58M.',
      'Food cost rose from 29% to 33% of sales; labor stayed at 32% of sales.',
      'Guest counts fell 15%; the average check rose 3%.',
      'Rent, utilities, marketing and other operating costs are fixed at about $22M a year.',
    ],
    asks: [
      'What was profit before and after? Walk the bridge.',
      'Which problem would you fix first?',
    ],
    hint: 'Split the profit swing into lost volume (with fixed costs that did not shrink) and higher food cost.',
    solution:
      "Before: $66M − $19.1M food (29%) − $21.1M labor (32%) − $22M fixed ≈ $3.7M profit. After: $58M − $19.1M food (33%) − $18.6M labor − $22M ≈ −$1.7M. The $5.4M swing splits into two parts. Volume: $8M of lost sales at a 39% contribution margin (100% − 29% − 32%) costs ~$3.1M because fixed costs did not shrink; the fall in sales is traffic (−15%) partly offset by check (+3%). Food cost: 4 extra points on $58M costs ~$2.3M. Fix traffic first, since it drives the larger loss and compounds: a value menu, a stronger lunch daypart and delivery partnerships. In parallel, re-engineer the menu to cut food cost back toward 30% (drop low-margin items, renegotiate protein contracts).",
  },
  {
    code: 'US-C-09',
    slug: 'cybersecurity-per-device-pricing',
    title: 'A cybersecurity company wants to switch from per-seat to per-device pricing',
    type: 'pricing',
    difficulty: 'hard',
    firm: 'L.E.K.',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'pri',
    industry: 'B2B software',
    situation:
      'A mid-market cybersecurity software company charges per user seat. Customers increasingly protect laptops, phones, sensors and shared devices, so the CFO wants to price per protected device instead. The CEO fears a customer backlash.',
    facts: [
      '1,200 customers, averaging 250 seats at $8 per seat per month.',
      'Proposed price: $6 per protected device per month; the average customer has 400 devices.',
      'Manufacturing customers average 3 devices per user; knowledge-work customers average 1.2.',
    ],
    asks: [
      'What happens to annual recurring revenue (ARR)?',
      'Who wins and who loses under the new model?',
      'How would you roll it out?',
    ],
    hint: 'Compute ARR per customer under both models, then look at the extremes of the customer mix.',
    solution:
      "Today each customer pays 250 × $8 = $2,000 a month, so ARR is 1,200 × $2,000 × 12 = $28.8M. Per device, the average customer pays 400 × $6 = $2,400 a month (+20%), taking ARR to ~$34.6M if nobody churns. The average hides a split: a manufacturing customer with 250 users and 3 devices each (750 devices) would pay $4,500 a month (+125%), while a knowledge-work customer at 1.2 devices per user (300 devices) would pay $1,800 (−10%). The risk is concentrated churn among the device-heavy customers who most need the product. Roll-out: price in device bands with a per-user cap, grandfather existing contracts for 12 months, and sell the change on value (every device protected). Aim for +10–15% ARR with churn below 5%.",
  },
  {
    code: 'US-C-10',
    slug: 'pet-retailer-buys-vet-clinics',
    title: 'Should a pet-supply retailer buy a veterinary clinic chain?',
    type: 'm&a',
    difficulty: 'medium',
    firm: 'EY-Parthenon',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'ma',
    industry: 'Retail & healthcare',
    situation:
      "A national pet-supply retailer is offered a chain of 150 veterinary clinics. Management likes the idea of putting clinics inside stores but worries about the 15x price.",
    facts: [
      'Retailer: 1,100 stores, revenue $6B, EBITDA margin 8%.',
      'Target: revenue $450M, EBITDA $70M, asking price $1.05B (15x EBITDA). Comparable clinic chains trade near 12x.',
      "40% of the retailer's stores have room for a clinic; an in-store clinic adds ~$150K a year of extra retail sales at a 30% margin.",
      'Procurement and shared marketing could save about $8M a year.',
    ],
    asks: [
      'What is the strategic rationale?',
      'What are the synergies worth?',
      'Is 15x justified? What would you recommend?',
    ],
    hint: 'Value the premium over a fair standalone multiple, then value the synergies at the same multiple and compare.',
    solution:
      "At a 12x sector multiple the clinics are worth ~$840M on their own, so the seller wants a ~$210M premium. Revenue synergy: co-locating 300 clinics (well below the 440 stores with space) adds 300 × $150K = $45M of retail sales, about $13.5M of EBITDA, worth ~$160M at 12x. Cost synergies of $8M a year are worth ~$96M. Total synergy value ≈ $255M, slightly above the premium, but only if co-location actually happens, which needs capex and vets in a tight labor market. Rationale is real: vet visits drive recurring store traffic and pharmacy sales. Recommendation: pursue, but offer ~14x with an earn-out tied to the co-location roll-out.",
  },
  {
    code: 'US-C-11',
    slug: 'ev-charger-installer-national',
    title: 'Taking a California EV home-charger installer national',
    type: 'go to market',
    difficulty: 'medium',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'ent',
    industry: 'Energy & EVs',
    situation:
      'VoltHome installs Level 2 home chargers in California and wants to go national. The founders are debating three models: their own installation crews, a marketplace of certified local electricians, or becoming the referred installer for an automaker.',
    facts: [
      'VoltHome does 18,000 installs a year at an average $1,600 (hardware plus labor) and a 25% gross margin.',
      'About 1.3M new EVs are sold in the US each year; roughly 70% of buyers install a home charger.',
      'A marketplace model would earn a 15% fee per install.',
      'A partner automaker would hold ~25% of US EV sales; about half of its referred buyers would book an install.',
    ],
    asks: [
      'How big is the national market?',
      'Compare the three models.',
      'What would you recommend?',
    ],
    hint: 'Size installs per year, then compare gross profit per install and how fast each model can scale.',
    solution:
      "The market is ~1.3M × 70% ≈ 910K installs a year, about $1.46B. Own crews keep ~$400 of gross profit per install but scale slowly: 10 metros covering ~45% of volume at a 6% share is ~25K installs, about $10M of gross profit. A marketplace earns $240 per install and scales fast: a 5% national share (~45K installs) is ~$11M, with quality risk. The automaker deal is a demand engine: 910K × 25% × 50% ≈ 114K installs, worth ~$45M at own-crew margins or ~$27M through the marketplace, but no crew network could absorb that volume quickly. Recommendation: sign the automaker partnership for near-zero acquisition cost, and fulfill it with own crews in the top five metros and certified electricians everywhere else.",
  },
  {
    code: 'US-C-12',
    slug: 'phoenix-hospital-er-crowding',
    title: "A Phoenix hospital's emergency department is overcrowded",
    type: 'operations',
    difficulty: 'hard',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 25,
    cluster: 'ops',
    industry: 'Healthcare',
    situation:
      "A 400-bed hospital in Phoenix has long emergency department waits and a growing number of patients who leave before being seen. The CEO's instinct is to expand the ED. She asks you to check that instinct.",
    facts: [
      'The ED sees 220 patients a day; average ED length of stay is 6.5 hours; 12% leave without being seen.',
      'A quarter of ED patients are admitted, and they wait an average 5 hours in the ED for an inpatient bed.',
      'Inpatient occupancy is 95%; average inpatient stay is 5 days; only 30% of discharges happen before noon.',
      'Each patient who leaves without being seen costs about $600 of lost margin.',
    ],
    asks: [
      'What is the problem costing?',
      'Where is the real bottleneck?',
      'What should the hospital do instead of, or before, expanding the ED?',
    ],
    hint: 'Follow the admitted patients: where do they wait, and why?',
    solution:
      "Patients leaving without being seen: 12% × 220 ≈ 26 a day × $600 ≈ $16K a day, about $5.8M a year. The bottleneck is inpatient flow, not ED capacity: 55 admitted patients a day each boarding ~5 hours consume ~275 ED bed-hours a day, equivalent to ~11 ED beds occupied around the clock. With occupancy at 95% and only 30% of discharges before noon, beds free up in the evening while admissions peak in the afternoon. Cutting average stay from 5 to 4.5 days would free ~38 beds (76 discharges a day × 0.5 days). Recommendation: don't build ED space yet. Run a capacity command center, set a 50% discharge-before-noon target (discharge lounge, earlier rounds, pharmacy and transport readiness), staff weekend discharges, and add a fast-track zone for low-acuity patients.",
  },
  {
    code: 'US-C-13',
    slug: 'low-cost-airline-unit-costs',
    title: "A low-cost airline's unit costs are rising faster than fares",
    type: 'profitability',
    difficulty: 'medium',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'prof',
    industry: 'Airlines',
    situation:
      "A US low-cost carrier's operating margin dropped from 9% to about 2% in one year. Fares have held up; costs have not. The CFO wants a cost bridge and a plan.",
    facts: [
      '120 narrow-body aircraft flying 30 billion available seat miles (ASMs) a year.',
      'Revenue per ASM is flat at 12.0 cents; cost per ASM rose from 10.9 to 11.8 cents.',
      'Fuel was 30% of costs, and the jet fuel price rose 20%.',
      'A new pilot contract added about $90M a year in crew costs.',
    ],
    asks: [
      'Build the bridge from 10.9 to 11.8 cents.',
      'Which drivers can management control?',
      'What would you recommend?',
    ],
    hint: 'Convert cents per ASM into dollars (× 30B ASMs), then attribute the increase to fuel and crew.',
    solution:
      "Revenue is 30B × 12.0¢ = $3.6B. Costs went from 10.9¢ ($3.27B, a 9% margin) to 11.8¢ ($3.54B, ~2%): +$270M. Fuel: 30% × $3.27B ≈ $981M × 20% ≈ $196M (~0.65¢). Pilots: $90M (~0.30¢). That is $286M, so ~$16M of other savings partly offset it. Management cannot control fuel prices or a signed contract, but it can control fuel burn (newer-engine aircraft, single-engine taxi, weight), crew productivity (block hours per pilot, scheduling), hedging policy, and revenue per passenger. Recommendation: raise ancillary revenue (bags, seats, bundles) by a few dollars per passenger, trim unprofitable off-peak flying, accelerate fleet renewal, and put a disciplined hedging program in place.",
  },
  {
    code: 'US-C-14',
    slug: 'beverage-giant-sparkling-water-deal',
    title: 'A beverage giant considers buying a fast-growing sparkling-water brand',
    type: 'm&a',
    difficulty: 'hard',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 25,
    cluster: 'ma',
    industry: 'Consumer packaged goods',
    situation:
      'A large US beverage company wants to buy a buzzy sparkling-water brand. The founders are asking $2.4B, which is 50x EBITDA. The CEO asks what would have to be true to pay that.',
    facts: [
      'Target: revenue $400M growing 25% a year, EBITDA margin 12%.',
      "The acquirer's distribution could take the brand from 60,000 to 180,000 retail outlets.",
      'Brands inside the acquirer typically reach a 22% EBITDA margin; similar deals are valued at about 15x EBITDA.',
    ],
    asks: [
      'What must be true to justify $2.4B?',
      'Quantify the synergies.',
      'What would you recommend?',
    ],
    hint: 'Work backward from the price: what revenue and margin, at a normal multiple, gets you to $2.4B?',
    solution:
      "Standalone, three years of 25% growth takes revenue to ~$781M and EBITDA to ~$94M at 12%, worth ~$1.4B at 15x. With distribution: each current outlet sells ~$6,700 a year; if the 120K new outlets sell half that, revenue rises by ~$400M to ~$800M before organic growth. At the acquirer's 22% margin that is ~$176M of EBITDA, worth ~$2.64B at 15x. So $2.4B is justified only if both the distribution lift and the margin convergence arrive within about three years. Risks: brand dilution in mass channels, cannibalizing the acquirer's own water brands, and founder departures. Recommendation: bid up to ~$2.2B upfront with an earn-out tied to revenue milestones, or start with a distribution partnership and an option to buy.",
  },
  {
    code: 'US-C-15',
    slug: 'chicago-parking-dynamic-pricing',
    title: 'Should a Chicago parking operator switch to dynamic pricing?',
    type: 'pricing',
    difficulty: 'easy',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 15,
    cluster: 'pri',
    industry: 'Real estate & mobility',
    situation:
      'A parking operator runs three downtown Chicago garages at one flat price. It turns cars away on weekdays and sits half empty on weekends. The owner wants to try weekday and weekend prices.',
    facts: [
      '2,400 spaces in total; flat price $30 a day.',
      'Weekday occupancy is 95%; weekend occupancy is 40%.',
      'At $38 on weekdays, demand would fall about 10%; at $15 on weekends, demand would rise about 50%.',
    ],
    asks: [
      'What is the revenue impact of $38 weekdays and $15 weekends?',
      'What would you recommend?',
    ],
    hint: 'Compute daily revenue before and after for weekdays and weekends separately, then weight by 5 and 2 days.',
    solution:
      "Weekdays: 2,400 × 95% = 2,280 cars × $30 = $68.4K a day. At $38 with 10% fewer cars: 2,052 × $38 ≈ $78.0K, +$9.6K a day. Weekends: 960 cars × $30 = $28.8K; at $15 with 50% more cars: 1,440 × $15 = $21.6K, −$7.2K a day. Net per week: +$48K − $14.4K = +$33.6K, about +$1.75M a year. The weekday increase is clearly right. The weekend cut is not: halving the price to gain 50% more cars loses money. Recommendation: raise weekday prices (and test $40+ at peak hours), keep weekends near $30, and use targeted promotions tied to events, restaurants and hotels to fill weekend space.",
  },
  {
    code: 'US-C-16',
    slug: 'cable-broadband-fixed-wireless',
    title: 'A cable company is losing broadband customers to 5G home internet',
    type: 'growth',
    difficulty: 'hard',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'ent',
    industry: 'Telecom',
    situation:
      "A US cable operator's broadband base, its profit engine, shrank last year as wireless carriers pushed cheap 5G home internet. The board wants to know how much is at risk and whether to cut prices.",
    facts: [
      '5M broadband subscribers paying $70 a month on average; broadband gross margin is about 75%.',
      'The company lost 300K subscribers net last year to fixed wireless priced at $50 a month.',
      'Fixed wireless now wins 45% of new connections in its footprint.',
      'Winning back a churned customer costs about $450.',
    ],
    asks: [
      'How much revenue and profit is at risk?',
      'Evaluate cutting price, targeted retention and a mobile bundle.',
      'Recommend a strategy.',
    ],
    hint: 'Compare the cost of a blanket price cut with the cost of targeting only the customers likely to leave.',
    solution:
      "Last year's losses alone cost 300K × $70 × 12 ≈ $252M of revenue, about $189M of gross profit. If the trend runs three years, ~$750M of annual revenue is gone. A blanket cut to $50 would give away 5M × $20 × 12 = $1.2B a year to keep customers who were mostly not leaving, so it is value-destroying. Targeted retention (say the ~20% most at risk, 1M customers, at $15 a month off) costs ~$180M a year and protects the base far more cheaply. A mobile bundle (reselling wireless service) typically cuts churn 30–40% among bundled households and raises lifetime value. Differentiate on speed and reliability where fiber-grade performance beats fixed wireless. Recommendation: no headline price cut; targeted retention offers plus an aggressive mobile bundle, and win-backs only where lifetime value exceeds the $450 cost.",
  },
  {
    code: 'US-C-17',
    slug: 'trucking-empty-miles',
    title: "A trucking company's empty miles are eating its margin",
    type: 'operations',
    difficulty: 'medium',
    firm: 'Oliver Wyman',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'ops',
    industry: 'Transportation',
    situation:
      "A truckload carrier's trucks drive more than a fifth of their miles empty. The CEO has heard that the best carriers run far fewer empty miles and wants to know what closing the gap is worth.",
    facts: [
      '1,500 trucks, each driving about 110,000 miles a year; 22% of miles are empty (deadhead).',
      'Revenue is $2.90 per loaded mile; variable cost is $1.90 per mile driven, loaded or empty.',
      'Industry leaders run 12–14% empty miles.',
    ],
    asks: [
      'What do empty miles cost today?',
      'What is reaching 14% worth?',
      'How would you get there?',
    ],
    hint: 'Hold total miles constant: every empty mile converted to a loaded one adds revenue without adding cost.',
    solution:
      "Total miles are 1,500 × 110K = 165M; 22% empty is ~36.3M miles × $1.90 ≈ $69M a year spent driving empty. At 14% empty with total miles unchanged, loaded miles rise from ~128.7M to ~141.9M, an extra ~13.2M loaded miles × $2.90 ≈ $38M of revenue with no extra cost, so almost all of it is profit. Levers: digital load matching and freight marketplaces for backhauls, dedicated round-trip lanes with large shippers, network design that balances inbound and outbound freight by region, and relay or drop-trailer networks. Recommendation: target 16% in year one through load-matching software and backhaul contracts, then 14% as dedicated lanes mature.",
  },
  {
    code: 'US-C-18',
    slug: 'florida-dental-group-georgia',
    title: 'Should a Florida dental group expand into Atlanta?',
    type: 'market entry',
    difficulty: 'easy',
    firm: 'Accenture Strategy',
    format: 'interviewer-led',
    minutes: 15,
    cluster: 'ent',
    industry: 'Healthcare services',
    situation:
      'A private-equity-backed dental group with 60 offices in Florida wants to expand into metro Atlanta. It can build new offices or buy existing practices.',
    facts: [
      'Average office revenue is $1.8M at an 18% EBITDA margin.',
      'Metro Atlanta has about 6.3M people; ~55% of adults visit a dentist each year, spending about $600 each.',
      'Building a new office costs $1.1M and takes about two years to mature; existing practices sell for ~5x EBITDA.',
    ],
    asks: [
      'Is Atlanta big enough?',
      'Build or buy?',
      'How would you enter?',
    ],
    hint: 'Compare payback on a build versus an acquisition, then check the share the plan implies.',
    solution:
      "Each office makes $1.8M × 18% ≈ $324K of EBITDA. Building costs $1.1M, a ~3.4-year payback after a two-year ramp. Buying a similar practice costs 5 × $324K ≈ $1.6M, a 5-year payback, but with patients and staff on day one. The market: 6.3M × 55% × $600 ≈ $2.1B of spend, so 30 offices ($54M) would be ~2.6% share, which is achievable. Recommendation: buy 5–8 anchor practices across the metro for patients and hiring, then build new offices around them in a hub-and-spoke model to lower average cost per office.",
  },
  {
    code: 'US-C-19',
    slug: 'insurer-cut-costs-15-percent',
    title: 'An auto and home insurer must cut operating costs by 15%',
    type: 'cost reduction',
    difficulty: 'medium',
    firm: 'Kearney',
    format: 'candidate-led',
    minutes: 20,
    cluster: 'ops',
    industry: 'Insurance',
    situation:
      "A US property and casualty insurer's expense ratio is above its peers. The CEO has promised investors a 15% cut in operating expenses (excluding claims payouts) and asks where the money is.",
    facts: [
      'Premiums $8B; operating expenses $1.6B.',
      'Breakdown: claims-handling staff $500M, IT $400M, agent commissions $450M, marketing $150M, corporate overhead $100M.',
      'Peers spend about 3.5% of premiums on IT.',
      'Simple claims (glass, minor damage) are 60% of claims and take about 40% of claims-handling effort.',
    ],
    asks: [
      'Where would you find $240M?',
      'How would you sequence it?',
    ],
    hint: 'Benchmark each line against peers or best practice. Be careful with commissions: they are tied to revenue.',
    solution:
      "The target is 15% × $1.6B = $240M. IT: $400M is 5% of premiums vs a 3.5% peer level, a ~$120M gap (cloud migration, vendor consolidation, retiring legacy systems). Claims: automating simple claims with photo-based estimating and straight-through processing could halve the ~40% of effort they take, ~$100M. Marketing: shifting from TV to targeted digital could save ~15%, ~$22M. Overhead: ~10%, ~$10M. That is ~$252M. Commissions are revenue-linked, so cut them only through channel mix (more direct and digital sales). Sequencing: quick wins in marketing and overhead in six months, then the larger claims automation and IT programs over 18–24 months.",
  },
  {
    code: 'US-C-20',
    slug: 'hardware-chain-big-box-threat',
    title: 'A Pacific Northwest hardware chain faces a big-box entrant',
    type: 'competitive strategy',
    difficulty: 'hard',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 25,
    cluster: 'soft',
    industry: 'Home improvement retail',
    situation:
      'A regional hardware and lumber chain has learned that a national big-box home-improvement retailer will open 12 stores in its region over the next two years. The CEO asks how bad this is and how to respond.',
    facts: [
      '85 stores; revenue $1.7B; gross margin 36%; operating margin 6%.',
      '30 of its stores are within 5 miles of a planned big-box site.',
      'Historically, nearby independent stores lose 15–25% of sales when a big box opens.',
      '45% of sales go to contractors (pros), who value delivery, trade credit and job-site ordering.',
    ],
    asks: [
      'Quantify the threat.',
      'Where can the chain win, and where should it not fight?',
      'What is your recommendation?',
    ],
    hint: 'Size the sales at risk, then compare the lost gross profit with total operating profit.',
    solution:
      "The 30 exposed stores carry roughly 35% of revenue, about $600M. Losing 15–25% of that is $90–150M of sales and $32–54M of gross profit, against operating profit of about $102M (6% of $1.7B), so up to half of profit is at risk. Don't fight on everyday price across the board. Defend where a big box is weaker: pros (45% of sales) through delivery, trade credit, dedicated pro desks and job-site ordering, and DIY convenience through small-format service. Convert the five most exposed stores into pro-focused yards, launch a contractor loyalty program, and consider selling or closing three or four of the weakest overlapping stores. Recommendation: a pro-first strategy that aims to protect ~70% of at-risk sales.",
  },
  {
    code: 'US-C-21',
    slug: 'pharma-patent-cliff',
    title: "A pharma company's top drug loses patent protection next year",
    type: 'profitability',
    difficulty: 'hard',
    firm: 'BCG',
    format: 'candidate-led',
    minutes: 25,
    cluster: 'prof',
    industry: 'Pharmaceuticals',
    situation:
      "A US specialty pharmaceutical company gets 60% of its revenue from one drug whose patent expires in 12 months. The CEO needs a plan for the cliff.",
    facts: [
      'The drug sells $1.2B a year; branded sales typically fall about 80% within a year of generic entry.',
      'An extended-release version would take 18 months and $150M to develop; it could keep about 30% of patients at brand price.',
      'An authorized-generic partner would pay about $60M a year.',
      'About $300M of the company’s $700M SG&A supports this drug.',
    ],
    asks: [
      'How big is the cliff?',
      'Evaluate the extended-release version, an authorized generic and SG&A cuts.',
      'What would you recommend?',
    ],
    hint: 'Compare year-two revenue with and without action, and watch the timing gap between expiry and the new formulation.',
    solution:
      "Without action, ~80% of $1.2B, about $960M, disappears within a year, leaving ~$240M. An extended-release version that keeps ~30% of patients protects ~$360M a year instead of ~$240M; it pays back its $150M quickly, but it arrives six months after the generics, so patients must be converted early (prescriber education, co-pay support) or many will already have switched. An authorized generic adds ~$60M a year of low-effort income. Resizing the SG&A that supports the drug by ~$200M protects margin. Year-two revenue from the franchise can be ~$420M instead of ~$240M. Recommendation: do all three, accelerate the reformulation, and start business development now to license or acquire late-stage assets that replace the revenue.",
  },
  {
    code: 'US-C-22',
    slug: 'new-england-bakery-cafe-growth',
    title: 'A New England bakery-café chain has hit a plateau',
    type: 'growth',
    difficulty: 'easy',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 15,
    cluster: 'ent',
    industry: 'Restaurants',
    situation:
      'A 28-unit bakery-café chain in Massachusetts and Connecticut has seen flat sales for two years. The owners want growth without betting the company on new stores.',
    facts: [
      'Average unit revenue is $1.5M; 60% of sales happen before 11 a.m.',
      'Lunch is about 25% of sales.',
      'Catering is 5% of sales, vs about 12% at peer chains.',
      'A new café costs $1.2M to open.',
    ],
    asks: [
      'What growth levers exist? Size them.',
      'What would you do first?',
    ],
    hint: 'Look for idle capacity in the existing stores before paying for new ones.',
    solution:
      "Revenue is 28 × $1.5M = $42M. Catering at the peer level adds ~7 points of sales, about +$2.9M, at high margin, using kitchen capacity that sits idle after the morning rush. Lunch: a 30% lift on the ~25% of sales that lunch represents adds ~$3.2M. Together that is ~$6M (+15%) with almost no capex. New cafés: five more would add ~$7.5M but cost ~$6M. Recommendation: build a catering sales team (offices, universities, hospitals) and a sharper lunch menu first, then open new units funded by the extra cash.",
  },
  {
    code: 'US-C-23',
    slug: 'bank-call-center-hold-times',
    title: "A bank's call center has long hold times",
    type: 'operations',
    difficulty: 'easy',
    firm: 'Deloitte',
    format: 'interviewer-led',
    minutes: 15,
    cluster: 'ops',
    industry: 'Banking',
    situation:
      "A regional US bank's customers wait nine minutes on hold and one in nine hangs up. Leadership assumes it needs more agents.",
    facts: [
      '1.8M calls a year; average handle time is 7 minutes; 280 agents, each with about 1,500 productive hours a year.',
      'Average hold time is 9 minutes; 11% of callers abandon.',
      '35% of calls are balance or transaction questions that the mobile app already answers.',
      'An agent costs about $55K a year, fully loaded.',
    ],
    asks: [
      'Is the center understaffed?',
      'What would you change?',
    ],
    hint: 'Compare total annual workload with total agent hours before assuming a headcount problem.',
    solution:
      "Workload is 1.8M × 7 minutes = 12.6M minutes, about 210K hours. Agents supply 280 × 1,500 ≈ 420K hours, so on average there is ample capacity; the holds come from peaks (Monday mornings, the start of the month, lunch hours) and from how shifts are scheduled. Moving half of the simple app-answerable calls (17.5% of volume) to digital removes ~37K hours, ~25 agent-equivalents or ~$1.4M a year, which can be redeployed to peaks. Add workforce-management scheduling to the hourly demand curve, a callback option instead of holds, and smarter IVR routing. Recommendation: no new hires; digital deflection plus peak scheduling, targeting holds under two minutes and abandonment under 4%.",
  },
  {
    code: 'US-C-24',
    slug: 'ev-maker-driver-assist-subscription',
    title: 'Should an EV maker sell driver-assist as a monthly subscription?',
    type: 'pricing',
    difficulty: 'medium',
    firm: 'McKinsey',
    format: 'interviewer-led',
    minutes: 20,
    cluster: 'pri',
    industry: 'Automotive',
    situation:
      'A US electric-vehicle maker sells its advanced driver-assist package as a one-time option. The product team wants to switch to a monthly subscription to build recurring revenue.',
    facts: [
      '200,000 vehicles a year; the $6,000 one-time option has a 25% take rate.',
      'Proposed subscription: $99 a month.',
      'Research: 45% of buyers would try the subscription and keep it about 30 months on average.',
    ],
    asks: [
      'Compare revenue per 100 vehicles under each model.',
      'What would you recommend?',
    ],
    hint: 'Per 100 cars: one-time buyers × price vs subscribers × monthly price × months kept.',
    solution:
      "One-time: 25 buyers × $6,000 = $150K per 100 vehicles, collected upfront. Subscription: 45 × $99 × 30 months ≈ $134K per 100 vehicles, collected over time, so it is lower on first owners alone. But it adds upside the one-time model lacks: later owners can subscribe, prices can rise as features improve, and a monthly trial converts buyers who would never pay $6,000 upfront. Recommendation: offer both. Keep the one-time option for buyers who want it, add the subscription at $99 (test $129 once features expand), and give subscribers a credit toward buying it outright. The goal is a combined take rate near 50%.",
  },
  {
    code: 'US-C-25',
    slug: 'hr-saas-acquires-rival',
    title: 'Should an HR software company buy a smaller rival?',
    type: 'm&a',
    difficulty: 'easy',
    firm: 'Bain',
    format: 'candidate-led',
    minutes: 15,
    cluster: 'ma',
    industry: 'B2B software',
    situation:
      'A US HR software company is offered a smaller competitor. The CEO likes the customer base but worries about overlap and the price.',
    facts: [
      "Acquirer: $300M of ARR growing 20% a year. Target: $40M of ARR with 2,000 customers; asking price $320M (8x ARR).",
      "30% of the target's ARR comes from customers who also use the acquirer.",
      "The acquirer's payroll module sells for $12K a year; about 25% of non-overlapping customers would buy it.",
      'Combining sales and back-office teams would save about $6M a year.',
    ],
    asks: [
      'What are the synergies worth?',
      'What are the risks?',
      'Should they buy, and at what price?',
    ],
    hint: 'Value revenue synergies with an ARR multiple and cost synergies with a profit multiple, then compare with the price.',
    solution:
      "Cross-sell: 70% of 2,000 = 1,400 non-overlapping customers × 25% × $12K ≈ $4.2M of new ARR, worth ~$34M at 8x. Cost synergies of $6M a year are worth ~$60M at ~10x. Total synergies ≈ $94M. The overlap is a risk: $12M of target ARR sits with shared customers who may consolidate onto one contract at a lower price. Other risks are product integration and churn during migration. At $320M the buyer keeps most of the synergy value, so the deal is attractive if churn stays low. Recommendation: buy, but offer ~$300M with part of the price as an earn-out linked to retention of the overlapping customers.",
  },
];
