import type { UsGuesstimate } from './types';

/**
 * US guesstimate bank, part 1 of 2 (US-G-01 .. US-G-25).
 * Worked answers are reasoned ESTIMATES built from stated assumptions — the
 * point is the structure and the sanity check, not an official statistic.
 */
export const US_GUESSTIMATES_A: UsGuesstimate[] = [
  {
    code: 'US-G-01',
    slug: 'gas-stations-in-the-us',
    title: 'How many gas stations are there in the United States?',
    difficulty: 'easy',
    firm: 'McKinsey',
    minutes: 10,
    scope: 'Count retail fuel stations open to the public in the US today. Exclude private fleet depots.',
    hint: 'Estimate total gasoline demand from the vehicle fleet, then divide by what an average station pumps in a day.',
    solution:
      "Demand: ~285M registered vehicles × ~0.9 fill-ups a week × ~10 gallons ≈ 133B gallons a year, about 365M gallons a day. Supply per station: an average station has ~6 nozzles, busy ~16 hours a day, with ~2.5 fill-ups per nozzle per hour at ~10 gallons, so ~2,400 gallons a day. Stations ≈ 365M ÷ 2,400 ≈ 150,000. Sanity check: that is one station per ~2,200 people, which matches the everyday sense that a town of 10,000 has four or five stations.",
  },
  {
    code: 'US-G-02',
    slug: 'starbucks-cups-manhattan',
    title: 'How many cups of coffee does Starbucks sell in Manhattan on a weekday?',
    difficulty: 'medium',
    firm: 'BCG',
    minutes: 12,
    scope: 'All drinks sold by Starbucks stores in Manhattan on an average weekday.',
    hint: 'Triangulate: stores × drinks per store (supply) versus daytime population × coffee habits × Starbucks share (demand).',
    solution:
      "Supply side: Manhattan has roughly 220 Starbucks stores; a busy city store serves ~750 drinks a day, so ~165K cups. Demand side: weekday daytime population is ~3.1M (1.6M residents plus commuters and tourists); ~60% drink coffee, ~40% of those buy it out on a given day (~744K cups), and Starbucks takes ~25% of coffee bought out, so ~186K. The two methods land close together; call it ~175K cups a day. Sanity check: 175K ÷ 220 stores ≈ 800 drinks per store, about one every 60–70 seconds over a 14-hour day, which is realistic for Midtown and FiDi stores.",
  },
  {
    code: 'US-G-03',
    slug: 'nyc-rideshare-trips-per-day',
    title: 'How many Uber and Lyft trips happen in New York City on an average day?',
    difficulty: 'medium',
    firm: 'Bain',
    minutes: 12,
    scope: 'App-based ride-hail trips starting in the five boroughs on an average day.',
    hint: 'Supply side: active vehicles × trips per vehicle. Demand side: residents and visitors × share riding today × trips.',
    solution:
      "Supply: ~80K licensed for-hire vehicles work app-based trips; ~70% are on the road on a given day, each doing ~12 trips, so ~670K trips. Demand: 8.3M residents × ~5% taking a ride-hail trip today × ~1.6 trips ≈ 665K, plus ~60K trips by visitors and airport travelers, so ~725K. Answer: roughly 700K trips a day. Sanity check: 700K trips over 8.3M residents is about one trip per 12 residents a day, plausible for a city where most people don't own a car but mainly use the subway.",
  },
  {
    code: 'US-G-04',
    slug: 'pizzas-sold-in-the-us',
    title: 'How many pizzas are sold in the US each year?',
    difficulty: 'easy',
    firm: 'Deloitte',
    minutes: 10,
    scope: 'Whole-pizza equivalents sold per year in the US: restaurants, delivery and frozen.',
    hint: 'Population × pizza occasions per person per year × how much of a pizza one person eats per occasion.',
    solution:
      "335M Americans eat pizza on ~23 occasions a year on average (about once every two weeks, higher for kids and young adults). A typical serving is ~3 slices of an 8-slice pizza, about 0.4 of a pizza. So 335M × 23 × 0.4 ≈ 3.1B pizzas a year. Sanity check: at ~$12 per pizza on average that is ~$37B of spend, in line with the size of the US pizza restaurant and frozen-pizza business.",
  },
  {
    code: 'US-G-05',
    slug: 'golf-balls-sold-in-the-us',
    title: 'How many golf balls are sold in the US each year?',
    difficulty: 'medium',
    firm: 'L.E.K.',
    minutes: 12,
    scope: 'New golf balls sold in the US per year (retail and pro shops).',
    hint: 'Golfers × rounds per golfer × balls lost or retired per round, then add gifts and practice use.',
    solution:
      "~26M Americans play golf on a course, averaging ~20 rounds a year, so ~520M rounds. A typical golfer loses or retires ~1.2 balls a round (beginners many more, good players fewer), so ~625M balls. Add ~15% for gifts, logo balls and practice, and sales come to ~720M balls, about 60M dozen. Sanity check: at ~$30 a dozen that is ~$1.8B, a believable size for the US golf-ball market.",
  },
  {
    code: 'US-G-06',
    slug: 'super-bowl-ad-revenue',
    title: 'How much ad revenue does the network earn from the Super Bowl broadcast?',
    difficulty: 'easy',
    firm: 'BCG',
    minutes: 10,
    scope: 'National in-game commercial revenue for the game broadcast itself (exclude pregame).',
    hint: 'Commercial minutes → number of 30-second slots → price per slot.',
    solution:
      "The game broadcast runs ~3.5 hours, and roughly 23% of it is commercials, ~48 minutes, or ~96 thirty-second slots. Some go to network promos, so ~86 are sold at around $7M each: 86 × $7M ≈ $600M. Sanity check: that is ~$170M an hour of airtime, far above any other TV event, which fits the Super Bowl's ~115M-plus audience.",
  },
  {
    code: 'US-G-07',
    slug: 'california-public-ev-chargers',
    title: 'How many public EV charging ports are there in California?',
    difficulty: 'medium',
    firm: 'McKinsey',
    minutes: 12,
    scope: 'Public Level 2 and DC fast-charging ports (connectors) in California today.',
    hint: 'Start from the number of EVs on the road and a sensible ratio of EVs per public port; cross-check with stations × ports per station.',
    solution:
      "California has ~1.5M plug-in vehicles on the road. Most charging happens at home, so one public port can serve roughly 25–30 EVs; at ~28 that is ~54K ports. Cross-check: ~11K public charging locations × ~5 ports each ≈ 55K. Answer: ~55K public ports. Sanity check: that is one port per ~700 Californians, noticeably denser than the US average, which fits California having roughly a third of the country's EVs.",
  },
  {
    code: 'US-G-08',
    slug: 'amazon-packages-per-day',
    title: 'How many packages does Amazon deliver in the US on an average day?',
    difficulty: 'medium',
    firm: 'Bain',
    minutes: 12,
    scope: 'Amazon packages delivered to US homes and businesses per day, all carriers.',
    hint: 'Segment households into Prime and non-Prime and estimate packages per household per week.',
    solution:
      "131M US households: ~55% (72M) have Prime and receive ~1.4 Amazon packages a week (~101M a week); the other ~59M receive ~0.25 a week (~15M). That is ~116M packages a week, ~16.5M a day, about 6B a year. Sanity check: 6B packages over 335M people is ~18 per person a year, about one every three weeks per person, which feels right.",
  },
  {
    code: 'US-G-09',
    slug: 'dogs-in-the-us',
    title: 'How many pet dogs live in the United States?',
    difficulty: 'easy',
    firm: 'Deloitte',
    minutes: 8,
    scope: 'Pet dogs in US households today.',
    hint: 'Households × share owning a dog × dogs per dog-owning household.',
    solution:
      "131M households × ~40% owning at least one dog ≈ 52M dog-owning households × ~1.5 dogs each ≈ 80M dogs. Sanity check: roughly one dog for every four Americans, consistent with how common dogs are in suburban neighborhoods.",
  },
  {
    code: 'US-G-10',
    slug: 'us-dog-food-market',
    title: 'Estimate the annual US market for dog food and treats in dollars.',
    difficulty: 'medium',
    firm: 'BCG',
    minutes: 12,
    scope: 'Annual consumer spend on dog food and treats in the US.',
    hint: 'Number of dogs × monthly food and treat spend, segmented by size or premium tier.',
    solution:
      "~80M dogs. Monthly spend varies: a small dog on standard kibble costs ~$20, a large dog on premium food $70+, and fresh-food subscribers pay far more; a blended average is ~$35 a month for food plus ~$8 for treats, ~$43 a month or ~$516 a year. 80M × $516 ≈ $41B. Sanity check: total US pet-food spending is commonly put in the $60B-plus range across dogs and cats, and dogs take the larger share.",
  },
  {
    code: 'US-G-11',
    slug: 'nfl-regular-season-tickets',
    title: 'How many tickets does the NFL sell in a regular season?',
    difficulty: 'easy',
    firm: 'McKinsey',
    minutes: 8,
    scope: 'Total attendance across all NFL regular-season games in one season.',
    hint: 'Games in a season × average attendance per game.',
    solution:
      "32 teams × 17 games ÷ 2 = 272 games. Average attendance is ~67K per game (stadiums hold 60–80K and most sell out). 272 × 67K ≈ 18.2M tickets. Sanity check: that is ~570K fans a team a season, or ~67K at each of about eight or nine home games.",
  },
  {
    code: 'US-G-12',
    slug: 'iphones-sold-in-the-us',
    title: 'How many iPhones are sold in the US each year?',
    difficulty: 'medium',
    firm: 'Bain',
    minutes: 10,
    scope: 'New iPhones sold in the US per year.',
    hint: 'Installed base of iPhone users ÷ replacement cycle, plus net new users.',
    solution:
      "~290M Americans use a smartphone and iPhone's share of users is ~55%, so ~160M iPhone users. People replace phones about every three years, giving ~53M replacements, plus ~2M net new users: ~55M iPhones a year. Sanity check: at ~$900 average that is ~$50B of US iPhone revenue, a plausible share of Apple's roughly $200B global iPhone business.",
  },
  {
    code: 'US-G-13',
    slug: 'school-buses-in-the-us',
    title: 'How many school buses are there in the US?',
    difficulty: 'easy',
    firm: 'Accenture Strategy',
    minutes: 10,
    scope: 'Yellow school buses in operation in the US.',
    hint: 'Students who ride × students each bus carries per day (runs per bus × riders per run).',
    solution:
      "~49M public K-12 students; about half (~24.5M) ride a school bus. A bus carries ~35 riders a run (rural routes run light) and makes ~1.5 runs each morning because schools stagger start times, so it serves ~52 students a day. 24.5M ÷ 52 ≈ 470K buses. Sanity check: that is about five buses per public school, reasonable once rural districts with long routes are included.",
  },
  {
    code: 'US-G-14',
    slug: 'costco-hot-dogs',
    title: 'How many hot dogs do Costco food courts sell in the US each year?',
    difficulty: 'easy',
    firm: 'BCG',
    minutes: 10,
    scope: 'Hot dog combos sold at US Costco warehouse food courts per year.',
    hint: 'Warehouses × shoppers per day × share buying a hot dog × days open.',
    solution:
      "~600 US warehouses × ~4,500 shopper visits a day ≈ 2.7M visits. About 15% buy the famous hot-dog combo, so ~405K a day × ~360 days ≈ 146M a year. Sanity check: ~680 hot dogs per warehouse per day, about one a minute over an 11-hour day at a busy food court.",
  },
  {
    code: 'US-G-15',
    slug: 'jfk-departing-passengers',
    title: 'How many passengers depart from JFK airport on an average day?',
    difficulty: 'medium',
    firm: 'Oliver Wyman',
    minutes: 12,
    scope: 'Departing passengers (including connections) at New York JFK on an average day.',
    hint: 'Departing flights × average seats × load factor.',
    solution:
      "JFK has ~550 departures a day. The mix is roughly one-third wide-body international flights (~300 seats) and two-thirds narrow-body domestic flights (~150), an average of ~190 seats. At an ~82% load factor: 550 × 190 × 0.82 ≈ 86K departing passengers a day. Sanity check: doubled for arrivals and multiplied by 365, that is ~63M passengers a year, in line with a top-10 US airport.",
  },
  {
    code: 'US-G-16',
    slug: 'thanksgiving-turkeys',
    title: 'How many turkeys do Americans eat on Thanksgiving?',
    difficulty: 'easy',
    firm: 'Deloitte',
    minutes: 8,
    scope: 'Whole turkeys cooked for Thanksgiving in the US.',
    hint: 'Households celebrating with turkey ÷ households sharing one bird.',
    solution:
      "131M households × ~88% celebrating with turkey ≈ 115M households. Many share a meal: on average ~2.5 households gather around one bird. 115M ÷ 2.5 ≈ 46M turkeys. Sanity check: at ~15 lb each that is ~700M lb of turkey, about 2 lb per American for one meal including leftovers.",
  },
  {
    code: 'US-G-17',
    slug: 'hair-salons-and-barbershops',
    title: 'How many hair salons and barbershops are there in the US?',
    difficulty: 'medium',
    firm: 'Kearney',
    minutes: 12,
    scope: 'Establishments offering haircuts (salons and barbershops) in the US.',
    hint: 'Annual haircut visits (demand) ÷ visits one shop can handle per year (supply).',
    solution:
      "Demand: ~165M males × ~8 cuts a year ≈ 1.3B visits; ~170M females × ~4 visits ≈ 0.7B; ~2B visits a year. Supply: a typical shop has ~4 chairs × ~8 clients per chair a day × ~300 days × ~70% utilization ≈ 6,700 visits a year. 2B ÷ 6,700 ≈ 300K establishments. Sanity check: one shop per ~1,100 people, consistent with a small town main street having several.",
  },
  {
    code: 'US-G-18',
    slug: 'airbnb-nights-us',
    title: 'How many nights are booked on Airbnb in the US each year?',
    difficulty: 'medium',
    firm: 'Bain',
    minutes: 12,
    scope: 'Nights booked at US Airbnb listings per year.',
    hint: 'Active listings × 365 × occupancy.',
    solution:
      "The US has ~1.2M actively rented Airbnb listings (more are listed but rarely booked). Average occupancy is ~45%, so 1.2M × 365 × 0.45 ≈ 197M nights, call it ~190M. Sanity check: at ~$180 a night that is ~$35B of bookings, a plausible share of US lodging spend.",
  },
  {
    code: 'US-G-19',
    slug: 'chick-fil-a-restaurant-revenue',
    title: 'What is the annual revenue of a typical Chick-fil-A restaurant?',
    difficulty: 'medium',
    firm: 'McKinsey',
    minutes: 12,
    scope: 'Annual sales of an average free-standing Chick-fil-A (closed Sundays).',
    hint: 'Transactions per day (by daypart and drive-thru) × average check × days open.',
    solution:
      "A busy free-standing unit runs two drive-thru lanes plus dine-in. Across breakfast, a very heavy lunch and a solid dinner, ~1,900 transactions a day is reasonable. At an ~$13 average check that is ~$24.7K a day × ~310 days (closed Sundays and a few holidays) ≈ $7.7M a year. Sanity check: well above a typical fast-food unit (~$2–3M), consistent with its reputation for long drive-thru lines moving quickly.",
  },
  {
    code: 'US-G-20',
    slug: 'evs-sold-in-the-us',
    title: 'How many electric vehicles are sold in the US each year?',
    difficulty: 'easy',
    firm: 'BCG',
    minutes: 8,
    scope: 'New battery-electric passenger vehicles sold in the US per year.',
    hint: 'Total new light-vehicle sales × EV share.',
    solution:
      "About 15.5M new light vehicles are sold in the US each year; battery-electric vehicles are ~8% of sales, so ~1.25M EVs. Sanity check: California alone buys roughly a third of them, and US EV share lags Europe and China, both consistent with ~8%.",
  },
  {
    code: 'US-G-21',
    slug: 'running-shoes-sold',
    title: 'How many pairs of running shoes are sold in the US each year?',
    difficulty: 'medium',
    firm: 'L.E.K.',
    minutes: 12,
    scope: 'Pairs of running shoes sold in the US per year, whether used for running or not.',
    hint: 'Segment buyers: serious runners, casual runners, and people who wear running shoes as everyday sneakers.',
    solution:
      "Serious runners (~15M) wear out ~2.5 pairs a year: ~37.5M. Casual runners (~35M) buy ~1 pair a year: ~35M. Non-runners buying running shoes as everyday or walking sneakers (~60M people) buy ~0.5 pair a year: ~30M. Total ≈ 100M pairs. Sanity check: at ~$110 a pair that is ~$11B, a believable slice of the ~$25B-plus US athletic footwear market.",
  },
  {
    code: 'US-G-22',
    slug: 'halloween-costume-spending',
    title: 'How much do Americans spend on Halloween costumes each year?',
    difficulty: 'easy',
    firm: 'Deloitte',
    minutes: 8,
    scope: 'Annual US spend on Halloween costumes for people and pets.',
    hint: 'People who dress up × average spend per costume (many reuse or DIY).',
    solution:
      "About 45% of Americans dress up (most kids, fewer adults), ~150M people. Average spend per person is ~$25, since many costumes are reused, homemade or borrowed. 150M × $25 ≈ $3.75B, plus a few hundred million for pet costumes: ~$4B. Sanity check: roughly $12 per American, about the price of one cheap mask.",
  },
  {
    code: 'US-G-23',
    slug: 'hospital-beds-in-the-us',
    title: 'How many hospital beds are there in the US?',
    difficulty: 'hard',
    firm: 'McKinsey',
    minutes: 15,
    scope: 'Staffed beds in all US hospitals, including specialty hospitals.',
    hint: 'Admissions × average length of stay = bed-days needed; divide by 365 and by average occupancy.',
    solution:
      "~34M hospital admissions a year × ~5.5 days average stay (short acute stays pulled up by long rehab and psychiatric stays) ≈ 187M bed-days, ~512K beds occupied on an average day. Hospitals run at ~65% average occupancy (peaks need slack), so ~790K beds; add ~10% for psychiatric, rehab and long-term care beds that the admissions figure understates: ~870K. Answer: about 850–900K. Sanity check: ~2.6 beds per 1,000 people, below most European countries, which matches the US's reputation for short stays.",
  },
  {
    code: 'US-G-24',
    slug: 'burgers-eaten-in-the-us',
    title: 'How many burgers do Americans eat each year?',
    difficulty: 'easy',
    firm: 'Bain',
    minutes: 8,
    scope: 'Hamburgers and cheeseburgers eaten in the US per year, at home and away.',
    hint: 'Population × burgers per person per week × 52.',
    solution:
      "335M Americans eat ~2.4 burgers a week on average (fast food, restaurants, backyard grills; vegetarians and small children pull the average down). 335M × 2.4 × 52 ≈ 42B burgers a year. Sanity check: at ~1/4 lb each that is ~10B lb of beef, a large but plausible share of total US beef consumption (~28B lb).",
  },
  {
    code: 'US-G-25',
    slug: 'weddings-in-the-us',
    title: 'How many weddings take place in the US each year?',
    difficulty: 'easy',
    firm: 'Accenture Strategy',
    minutes: 10,
    scope: 'Marriages (weddings) in the US per year, first marriages and remarriages.',
    hint: 'People reaching typical marrying age each year × share who marry × marriages per person ÷ 2 people per wedding.',
    solution:
      "Each single year of age has ~4.4M Americans. About 80% marry at some point, and counting remarriages there are ~1.2 marriages per person who marries, so ~4.4M × 0.8 × 1.2 ≈ 4.2M people marry each year, or ~2.1M weddings. Sanity check: ~5,800 weddings a day, concentrated on summer and fall Saturdays, which matches how hard popular venues are to book.",
  },
];
