import type { UsGuesstimate } from './types';

/**
 * US guesstimate bank, part 2 of 2 (US-G-26 .. US-G-50).
 * Worked answers are reasoned ESTIMATES built from stated assumptions.
 */
export const US_GUESSTIMATES_B: UsGuesstimate[] = [
  {
    code: 'US-G-26',
    slug: 'us-wedding-market-size',
    title: 'Estimate the size of the US wedding market in dollars.',
    difficulty: 'medium',
    firm: 'BCG',
    minutes: 12,
    scope: 'Annual spend on weddings in the US: ceremony, reception, attire, photography and flowers. Exclude engagement rings and honeymoons.',
    hint: 'Weddings per year × average spend per wedding; be careful that a few lavish weddings pull the average above the typical one.',
    solution:
      "~2.1M weddings a year. Spend is highly skewed: courthouse and small weddings cost a few thousand dollars, while large weddings with 150 guests often exceed $50K. A blended average of ~$25K per wedding (below the headline averages quoted for engaged couples who hire planners) gives 2.1M × $25K ≈ $52B. Sanity check: ~$160 per American per year, or a few percent of annual household discretionary spend spread across the relatively few households holding a wedding.",
  },
  {
    code: 'US-G-27',
    slug: 'soft-drink-servings-per-day',
    title: 'How many 12-ounce servings of soft drinks do Americans drink each day?',
    difficulty: 'easy',
    firm: 'Deloitte',
    minutes: 8,
    scope: 'Carbonated soft drinks (cans, bottles and fountain) per day in the US, in 12-oz servings.',
    hint: 'Annual gallons per person → ounces → 12-oz servings → per day × population.',
    solution:
      "Americans drink roughly 36 gallons of carbonated soft drinks per person a year: 36 × 128 oz ≈ 4,600 oz ÷ 12 ≈ 384 servings, about 1.05 a day. × 335M ≈ 350M servings a day. Sanity check: plenty of people drink none and heavy drinkers have three or four a day, which averages to about one each.",
  },
  {
    code: 'US-G-28',
    slug: 'coffee-shops-in-the-us',
    title: 'How many coffee shops are there in the US?',
    difficulty: 'medium',
    firm: 'Bain',
    minutes: 12,
    scope: 'Dedicated coffee shops (chains and independents). Exclude fast-food restaurants and gas stations.',
    hint: 'Coffee-shop purchases per day (demand) ÷ transactions per shop per day (supply).',
    solution:
      "~260M adults; ~66% drink coffee (~172M). They buy from a coffee shop ~1.2 times a week on average, so ~206M purchases a week, ~29.5M a day. A blended shop does ~700 transactions a day (busy chain stores near 900, independents nearer 300). 29.5M ÷ 700 ≈ 42K shops. Sanity check: one coffee shop per ~8,000 people, fitting a suburb of 40,000 with five or six.",
  },
  {
    code: 'US-G-29',
    slug: 'nyc-subway-weekday-rides',
    title: 'How many subway rides are taken in New York City on a typical weekday?',
    difficulty: 'medium',
    firm: 'McKinsey',
    minutes: 12,
    scope: 'Paid subway entries in NYC on an average weekday.',
    hint: 'Commuters who use the subway × 2 trips, plus non-work trips.',
    solution:
      "~4.5M people work in NYC; ~40% commute by subway, ~1.8M people × 2 trips ≈ 3.6M rides. Add students, errands, evening trips and tourists, ~0.6M more: ~4.2M rides a weekday. Sanity check: about half of the city's residents taking one subway ride on a typical weekday feels right for a transit-dependent city.",
  },
  {
    code: 'US-G-30',
    slug: 'tennis-balls-sold',
    title: 'How many tennis balls are sold in the US each year?',
    difficulty: 'medium',
    firm: 'L.E.K.',
    minutes: 12,
    scope: 'New tennis balls sold in the US per year, for any use.',
    hint: 'Segment by frequent players, casual players and a non-tennis use that is easy to forget.',
    solution:
      "Frequent players (~5M) open ~12 cans a year: ~60M cans. Casual players (~18M) buy ~1.5 cans: ~27M. Dog owners buying tennis balls as toys add ~5M cans. Total ~92M cans × 3 balls ≈ 280M balls. Sanity check: at ~$4 a can that is ~$370M, a plausible size for a mature sporting-goods category.",
  },
  {
    code: 'US-G-31',
    slug: 'people-in-the-air-over-the-us',
    title: 'At the busiest moment of a weekday, how many people are in the air on commercial flights over the US?',
    difficulty: 'hard',
    firm: 'BCG',
    minutes: 15,
    scope: 'Passengers and crew aboard airborne commercial flights over the US at the daily peak.',
    hint: 'Flights per hour × average time airborne = planes in the air; × people per plane.',
    solution:
      "~27K commercial passenger flights a day, mostly spread over ~16 active hours: ~1,700 departures an hour. Average airborne time is ~2.2 hours, so ~3,700 planes are in the air at a busy moment. With ~130 passengers and ~5 crew each: 3,700 × 135 ≈ 500K people. Sanity check: flight-tracking maps showing several thousand planes over the US at midday are consistent with ~3,700 commercial aircraft plus general aviation.",
  },
  {
    code: 'US-G-32',
    slug: 'piano-tuners-in-the-us',
    title: 'How many piano tuners work in the United States?',
    difficulty: 'easy',
    firm: 'McKinsey',
    minutes: 10,
    scope: 'People who tune pianos professionally, full-time equivalent.',
    hint: 'Pianos × tunings per piano per year ÷ tunings one tuner can do per year.',
    solution:
      "~131M households × ~7% with a piano ≈ 9.2M, plus ~1M in schools, churches and studios: ~10.2M pianos. Many are rarely tuned, so on average ~0.5 tunings a year: ~5.1M tunings. A tuner does ~4 a day × ~240 days ≈ 960 a year. 5.1M ÷ 960 ≈ 5,300 tuners. Sanity check: one tuner per ~60K people, so a mid-size city has a handful, which fits.",
  },
  {
    code: 'US-G-33',
    slug: 'credit-card-transactions-per-day',
    title: 'How many credit card transactions happen in the US on an average day?',
    difficulty: 'hard',
    firm: 'Oliver Wyman',
    minutes: 15,
    scope: 'Credit card (not debit) purchase transactions in the US per day, in-store and online.',
    hint: 'Adults with a credit card × share actively using one × transactions per active cardholder per day.',
    solution:
      "~260M adults; ~73% (~190M) have a credit card. ~80% use one regularly (~152M). An active user swipes, taps or clicks ~0.9 times a day (groceries, gas, subscriptions, online orders). 152M × 0.9 ≈ 137M transactions a day, ~50B a year. Sanity check: at ~$90 average that is ~$4.5T a year, in the range of annual US credit card purchase volume. Debit cards add even more transactions at a lower average ticket.",
  },
  {
    code: 'US-G-34',
    slug: 'self-storage-industry-revenue',
    title: 'Estimate the annual revenue of the US self-storage industry.',
    difficulty: 'hard',
    firm: 'Bain',
    minutes: 15,
    scope: 'Annual rental revenue of self-storage facilities in the US.',
    hint: 'Rented units (households plus businesses) × average monthly rent × 12.',
    solution:
      "About 11% of households rent a storage unit (~14.4M), and small businesses and contractors add ~1.6M more: ~16M rented units. Units range from a $60 locker to a $300 climate-controlled 10x30; a blended average of ~$160 a month gives 16M × $160 × 12 ≈ $31B. Sanity check: ~$230 per household a year across all households, and the industry's visibility (facilities on every suburban highway) supports a figure in the tens of billions.",
  },
  {
    code: 'US-G-35',
    slug: 'real-christmas-trees-sold',
    title: 'How many real Christmas trees are sold in the US each year?',
    difficulty: 'easy',
    firm: 'Deloitte',
    minutes: 8,
    scope: 'Real (cut or potted) Christmas trees bought in the US per year.',
    hint: 'Households putting up a tree × share choosing a real tree.',
    solution:
      "~131M households × ~75% putting up a tree ≈ 98M trees in homes. About 80% are artificial trees reused for years; ~20% are real trees bought fresh each year: ~20M real trees. Sanity check: at ~$80 each that is ~$1.6B, a believable size for tree farms and seasonal lots.",
  },
  {
    code: 'US-G-36',
    slug: 'basketballs-sold',
    title: 'How many basketballs are sold in the US each year?',
    difficulty: 'medium',
    firm: 'Accenture Strategy',
    minutes: 10,
    scope: 'New basketballs sold in the US per year, all sizes.',
    hint: 'Players × share buying a ball each year, plus institutional buyers and gifts.',
    solution:
      "~27M Americans play basketball at least occasionally. Balls last ~2–3 years, so ~40% of players buy one in a given year: ~10.8M. Schools, gyms, leagues and camps add ~2M, and gifts to non-players ~1M: ~14M basketballs a year. Sanity check: at ~$30 each that is ~$420M, a mid-sized sporting-goods category.",
  },
  {
    code: 'US-G-37',
    slug: 'solar-panels-installed-per-year',
    title: 'How many solar panels are installed in the US each year?',
    difficulty: 'hard',
    firm: 'McKinsey',
    minutes: 15,
    scope: 'Solar modules (panels) installed per year in the US, all segments.',
    hint: 'Estimate installed capacity by segment (residential, commercial, utility-scale) in watts, then divide by watts per panel.',
    solution:
      "Residential: ~700K systems × ~7 kW ≈ 4.9 GW. Commercial and community solar: ~2 GW. Utility-scale solar farms dominate at ~33 GW. Total ≈ 40 GW a year. A modern panel is ~400 W, so 40 GW ÷ 400 W ≈ 100M panels. Sanity check: about 270K panels installed a day; a single 100 MW solar farm alone uses ~250K panels, so a year of utility-scale projects easily accounts for most of the total.",
  },
  {
    code: 'US-G-38',
    slug: 'toilet-paper-rolls-per-year',
    title: 'How many rolls of toilet paper do Americans use each year?',
    difficulty: 'easy',
    firm: 'BCG',
    minutes: 8,
    scope: 'Standard-size toilet paper rolls used per year in the US (homes and away from home).',
    hint: 'Sheets per person per day → rolls per person per year → × population.',
    solution:
      "A person uses roughly 57 sheets a day: ~20.8K sheets a year. A standard roll has ~200 sheets, so ~104 rolls per person a year. × 335M ≈ 35B rolls. Sanity check: two rolls a week per person, which matches a family of four going through a 12-pack in about a week and a half.",
  },
  {
    code: 'US-G-39',
    slug: 'food-delivery-orders-per-day',
    title: 'How many food-delivery app orders are placed in the US each day?',
    difficulty: 'medium',
    firm: 'Bain',
    minutes: 12,
    scope: 'Restaurant delivery orders through apps such as DoorDash, Uber Eats and Grubhub per day in the US.',
    hint: 'Adults who use delivery apps × orders per user per month ÷ 30.',
    solution:
      "~260M adults × ~35% who order through delivery apps ≈ 91M users. An average user orders ~3 times a month (heavy users weekly or more, light users once a quarter), so ~273M orders a month, ~9M a day. Sanity check: at a ~$35 basket that is ~$115B a year of food ordered, consistent with delivery becoming a large slice of US restaurant sales.",
  },
  {
    code: 'US-G-40',
    slug: 'pickleball-paddle-market',
    title: 'Estimate the annual US market for pickleball paddles.',
    difficulty: 'medium',
    firm: 'L.E.K.',
    minutes: 12,
    scope: 'Annual US retail sales of pickleball paddles, in dollars.',
    hint: 'Split buyers into new players and existing players replacing or upgrading paddles.',
    solution:
      "~14M Americans play pickleball. New players (~5M a year) buy ~1.5 paddles each (often a two-pack): ~7.5M. Existing players (~9M) replace or upgrade about every 18 months: ~6M. Total ~13.5M paddles × ~$70 average (from $30 starter sets to $200+ carbon paddles) ≈ $950M. Sanity check: close to $1B for a sport that exploded in a few years is consistent with how visible it has become in retail.",
  },
  {
    code: 'US-G-41',
    slug: 'walt-disney-world-daily-visitors',
    title: 'How many people visit the four Walt Disney World theme parks on an average day?',
    difficulty: 'medium',
    firm: 'BCG',
    minutes: 10,
    scope: 'Combined daily attendance of Magic Kingdom, EPCOT, Hollywood Studios and Animal Kingdom.',
    hint: 'Estimate each park’s average daily attendance from its size and capacity, then add.',
    solution:
      "Magic Kingdom is the busiest, ~50K on an average day; EPCOT ~33K; Hollywood Studios ~28K; Animal Kingdom ~25K. Total ≈ 136K a day, ~50M park visits a year. Sanity check: with ~4 park days per trip that is ~12M trips a year, reasonable for the world's most-visited resort.",
  },
  {
    code: 'US-G-42',
    slug: 'birthday-cakes-sold',
    title: 'How many birthday cakes are sold in the US each year?',
    difficulty: 'easy',
    firm: 'Deloitte',
    minutes: 8,
    scope: 'Store-bought or bakery birthday cakes (not homemade) purchased per year in the US.',
    hint: 'Everyone has a birthday: split kids and adults and estimate the share celebrated with a bought cake.',
    solution:
      "~73M children: ~70% get a bought cake, ~51M. ~262M adults: ~25% get one, ~65M. Total ≈ 116M cakes a year, about 320K a day. Sanity check: a supermarket bakery selling ~15 birthday cakes a day across ~20K bakery-equipped grocery stores accounts for most of that.",
  },
  {
    code: 'US-G-43',
    slug: 'new-homes-built-in-texas',
    title: 'How many new homes are built in Texas each year?',
    difficulty: 'hard',
    firm: 'McKinsey',
    minutes: 15,
    scope: 'New housing units (single-family and apartments) completed in Texas per year.',
    hint: 'Population growth → new households, plus replacement of old homes and second homes or vacancy.',
    solution:
      "Texas has ~31M people growing ~1.5% a year, ~465K new residents; at ~2.6 people per household that is ~180K new households. Replacement of demolished or obsolete homes (~0.3% of ~11.5M units) adds ~35K, and vacancy and second homes ~10K. Total ≈ 225K new units a year. Sanity check: that is roughly one in seven new US homes for a state with one in eleven Americans, consistent with Texas leading the country in construction.",
  },
  {
    code: 'US-G-44',
    slug: 'atms-in-the-us',
    title: 'How many ATMs are there in the United States?',
    difficulty: 'medium',
    firm: 'Oliver Wyman',
    minutes: 12,
    scope: 'Bank-owned and independently owned ATMs in the US.',
    hint: 'Segment locations: bank branches, gas stations and convenience stores, and other retail and hospitality.',
    solution:
      "~76K bank branches × ~2 ATMs ≈ 152K. ~150K gas stations and convenience stores, about half with an ATM, ≈ 75K. Other locations (bars, restaurants, grocery stores, malls, hotels, casinos, airports) ≈ 220K independently owned machines. Total ≈ 450K ATMs. Sanity check: one ATM per ~750 people, and most Americans can find one within a short walk or drive.",
  },
  {
    code: 'US-G-45',
    slug: 'mlb-team-ticket-revenue',
    title: 'How much ticket revenue does a Major League Baseball team make in a season?',
    difficulty: 'easy',
    firm: 'Bain',
    minutes: 8,
    scope: 'Regular-season ticket revenue for an average MLB team.',
    hint: 'Home games × average attendance × average ticket price.',
    solution:
      "81 home games × ~29K average attendance × ~$40 average ticket (bleachers under $20, premium seats in the hundreds) ≈ $94M. Sanity check: well under a quarter of a typical team's total revenue, which also includes national and local TV, sponsorship and concessions.",
  },
  {
    code: 'US-G-46',
    slug: 'gallons-of-paint-sold',
    title: 'How many gallons of house paint are sold in the US each year?',
    difficulty: 'hard',
    firm: 'Kearney',
    minutes: 15,
    scope: 'Architectural paint (interior and exterior, homes and commercial buildings) sold per year in the US.',
    hint: 'Residential interior repainting, residential exterior repainting and new construction, then scale up for commercial buildings.',
    solution:
      "Interior: ~131M households repaint about two rooms a year at ~1.5 gallons each: ~3 gallons × 131M ≈ 390M. Exterior: ~90M single-family homes repainted every ~8 years with ~15 gallons: ~170M. New homes: ~1.5M a year × ~40 gallons ≈ 60M. Residential ≈ 620M gallons; if commercial and institutional buildings are ~25% of the total, the market is ~620M ÷ 0.75 ≈ 830M gallons. Sanity check: at ~$40 a gallon that is ~$33B, a plausible size for the US architectural-coatings market.",
  },
  {
    code: 'US-G-47',
    slug: 'gym-goers-per-weekday',
    title: 'How many Americans go to a gym on a typical weekday?',
    difficulty: 'easy',
    firm: 'Accenture Strategy',
    minutes: 8,
    scope: 'People visiting a gym or fitness club in the US on an average weekday.',
    hint: 'Gym members × share who visit on a given weekday.',
    solution:
      "~72M Americans hold a gym or fitness-club membership. Many rarely go; the average member visits ~2 times a week, so on a given weekday ~30% show up: ~22M people. Sanity check: a typical gym with ~4,000 members sees ~1,200 visits a day, busy but manageable across early-morning, lunch and evening peaks.",
  },
  {
    code: 'US-G-48',
    slug: 'car-wash-industry-revenue',
    title: 'Estimate the annual revenue of the US car-wash industry.',
    difficulty: 'medium',
    firm: 'BCG',
    minutes: 12,
    scope: 'Annual spend at professional car washes (tunnel, in-bay and hand wash) in the US.',
    hint: 'Segment vehicle owners by how often they use a professional wash, then × average price.',
    solution:
      "~285M vehicles. ~30% are washed professionally about monthly (~85.5M × 12 ≈ 1.03B washes); another ~30% a few times a year (~85.5M × 4 ≈ 340M); the rest wash at home or rarely. ~1.37B washes × ~$15 average ≈ $20B. Sanity check: ~$70 per vehicle a year across the whole fleet, consistent with the spread of express washes and unlimited monthly memberships.",
  },
  {
    code: 'US-G-49',
    slug: 'chickens-eaten-per-year',
    title: 'How many chickens are eaten in the US each year?',
    difficulty: 'medium',
    firm: 'Deloitte',
    minutes: 10,
    scope: 'Broiler chickens raised for meat and consumed in the US per year.',
    hint: 'Pounds of chicken per person per year × population ÷ edible pounds per bird.',
    solution:
      "Americans eat roughly 100 lb of chicken per person a year: 335M × 100 ≈ 33.5B lb. A broiler yields ~3.7 lb of retail meat, so 33.5B ÷ 3.7 ≈ 9B chickens a year. Sanity check: ~25M chickens a day, which sounds enormous until you consider wings, nuggets and grocery chicken breasts together.",
  },
  {
    code: 'US-G-50',
    slug: 'college-applications-per-year',
    title: 'How many college applications are submitted in the US each year?',
    difficulty: 'medium',
    firm: 'McKinsey',
    minutes: 12,
    scope: 'Undergraduate applications to US colleges per admissions cycle, including transfer and international applicants.',
    hint: 'High-school graduates who apply × applications per applicant, plus transfer and international applicants.',
    solution:
      "~3.8M US high-school graduates a year; ~70% apply to college (~2.66M). Selective-college applicants file 6–10 applications while community-college students file one, averaging ~4.5: ~12M. Transfer and international applicants add ~2M. Total ≈ 14M applications. Sanity check: selective colleges each receiving tens of thousands of applications, with hundreds of such schools, is consistent with a total in the low tens of millions.",
  },
];
