import Link from 'next/link';
import Logo from '@/components/logo';
import ThemeToggle from '@/components/theme-toggle';
import AuthCTA from '@/components/auth-cta';
import Footer from '@/components/footer';
import ScrollAnimations from '@/components/scroll-animations';
import { Card } from '@/components/ui/card';
import {
  Shield, Trophy, BookOpen, Newspaper, Building2,
  GraduationCap, Layers, CheckCircle2, ArrowRight, ChevronRight, HelpCircle,
} from 'lucide-react';
import {
  genericArticleJsonLd, genericBreadcrumbJsonLd, faqPageJsonLd,
} from '@/lib/seo';

export const metadata = {
  title: 'About us',
  description:
    'MECE (mece.in) is an independent online MBA & PGDM placement-interview prep platform for Indian students — free casebook, rubric-scored case & guesstimate practice, daily GD briefs, and a national leaderboard. The story and the method behind it.',
  alternates: { canonical: '/about' },
};

const articleJsonLd = genericArticleJsonLd({
  title: 'About MECE',
  description:
    'What MECE is, who it is for, and the method behind it — India\'s structured placement-interview prep platform for MBA and PGDM students.',
  url: '/about',
  datePublished: '2025-01-01',
  dateModified: '2026-07-14',
});

const breadcrumbJsonLd = genericBreadcrumbJsonLd([
  { name: 'Home', url: '/' },
  { name: 'About' },
]);

const ABOUT_FAQS = [
  {
    question: 'Is mece.in related to the MECE framework?',
    answer:
      'MECE the platform (mece.in) is named after the MECE principle (Mutually Exclusive, Collectively Exhaustive) but is a separate thing. The principle is a consulting problem-solving concept; mece.in is an online product that helps Indian MBA and PGDM students practise and get scored for placement interviews.',
  },
  {
    question: 'Is MECE affiliated with McKinsey, BCG, Bain, or any B-school?',
    answer:
      'No. MECE is an independent educational platform. It is not affiliated with, endorsed by, or connected to any consulting firm or business school referenced on the site. All trademarks belong to their respective owners.',
  },
  {
    question: 'Who runs MECE?',
    answer:
      'A small, independent team that went through the Indian B-school placement circuit themselves. MECE is deliberately presented at the organisation level rather than around individuals: the methodology, rubric, and casebook are fully public, and the platform asks to be judged on those. It is not run by, or affiliated with, any consulting firm or business school.',
  },
  {
    question: 'Who is MECE for?',
    answer:
      'Indian MBA and PGDM students at institutes such as the IIMs, FMS, XLRI, MDI, SPJIMR, NMIMS, and others who are preparing for summer-internship and final placements in consulting, finance, marketing, product, and operations.',
  },
  {
    question: 'Do I need to pay to use it?',
    answer:
      'No. The MECE Casebook — frameworks, worked cases, and guesstimates — is free to read without an account. Scored practice, daily GD briefs, and the leaderboard require a free account, with optional paid plans for unlimited practice.',
  },
  {
    question: 'Is the feedback generated by AI?',
    answer:
      'Yes — every submission is scored by MECE\'s evaluation engine against a fixed 100-point, six-dimension consulting rubric. An independent arithmetic backstop re-checks the numbers in guesstimates, so the score reflects real reasoning — not guesswork, and not generic chatbot output. The same rubric runs on every submission, which is what makes scores comparable across all of India.',
  },
];
const aboutFaqJsonLd = faqPageJsonLd(ABOUT_FAQS);

const WHAT_YOU_GET = [
  {
    icon: BookOpen,
    title: 'The free MECE Casebook',
    body:
      'A structured, openly readable curriculum: core frameworks (profitability, market entry, growth, pricing, M&A), a toolkit (Porter, SWOT, BCG, value chain), 25+ worked case interviews, 25+ multi-tier guesstimates, industry primers, and a zero-to-podium case-competition track.',
  },
  {
    icon: Shield,
    title: 'Six-dimension rubric scoring',
    body:
      'Submit a case or guesstimate and get a 100-point breakdown — Structure, Quantitative, Synthesis, Business Judgment, Creativity, and Professional Tone — with written feedback in about 60 seconds, plus an arithmetic backstop that verifies your math.',
  },
  {
    icon: Newspaper,
    title: 'Daily GD briefs',
    body:
      'Group-discussion briefs built fresh from live news — with smart angles, counter-arguments, and opening lines, structured for the GD format rather than served as plain news summaries.',
  },
  {
    icon: Trophy,
    title: 'A national leaderboard',
    body:
      'Earn points on every submission and brief, and track your percentile against MBA aspirants across India in real time — a milestone ladder from Day-0 Dreamer to the top of the table.',
  },
  {
    icon: Building2,
    title: 'Industry primers',
    body:
      'Concise primers on the sectors that show up in cases and interviews — asset management, aviation, banking, EVs, FMCG, healthcare, and more — so you walk in with context, not blanks.',
  },
  {
    icon: GraduationCap,
    title: 'Built around the Indian circuit',
    body:
      'Cases and guesstimates set in the Indian context (kirana GMV, UPI volumes, IPL economics, regional FMCG) and tuned to how summer and final placements actually run at Indian B-schools.',
  },
];

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-muted flex flex-col">
      {/* JSON-LD structured data */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(aboutFaqJsonLd) }} />
      <ScrollAnimations />

      {/* Static nav */}
      <nav className="sticky top-0 z-50 bg-background/90 backdrop-blur-sm border-b border-border w-full">
        <div className="container flex h-14 md:h-16 items-center justify-between">
          <Link href="/" className="flex items-center -ml-2 shrink-0">
            <Logo isLanding />
          </Link>
          <div className="flex items-center gap-2 md:gap-4 shrink-0">
            <ThemeToggle />
            <AuthCTA variant="nav" />
          </div>
        </div>
      </nav>

      <main className="container max-w-5xl py-16 flex-grow">

        {/* ── Hero: entity-first ─────────────────────────────────────── */}
        <header className="max-w-3xl mx-auto text-center mb-12" data-reveal>
          <p className="text-sm font-semibold uppercase tracking-wider text-primary">About MECE</p>
          <h1 className="mt-3 text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight text-foreground leading-tight">
            Built from inside the placement grind
          </h1>
          <p className="mt-6 text-lg leading-relaxed text-muted-foreground">
            <strong className="text-foreground">MECE</strong> (<span className="text-foreground">mece.in</span>) began the way most placement prep does: 2 AM peer mocks, seniors' PDFs passed down like heirlooms, and feedback that changed depending on who was across the table. It is now an independent, rubric-scored prep platform for Indian MBA and PGDM students — a free 145+ page casebook, practice graded on a fixed 100-point rubric, and a leaderboard that tells you where you actually stand.
          </p>
          <p className="mt-3 text-sm text-muted-foreground/80">
            The name is a nod to the consulting principle <strong className="text-foreground/70">MECE</strong> —
            <span className="italic"> Mutually Exclusive, Collectively Exhaustive</span> — which we also style as our
            tagline, <span className="italic">Method for Evaluating Corporate Excellence</span>.
          </p>
        </header>

        {/* Stats strip */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 max-w-3xl mx-auto mb-20" data-reveal>
          {[
            ['145+', 'Casebook pages'],
            ['6', 'Scoring dimensions'],
            ['Free', 'Casebook access'],
            ['India', 'Built for placements'],
          ].map(([v, l]) => (
            <Card key={l} className="p-4 text-center">
              <p className="text-2xl font-bold text-foreground">{v}</p>
              <p className="mt-1 text-xs text-muted-foreground">{l}</p>
            </Card>
          ))}
        </div>

        {/* ── Disambiguation callout ─────────────────────────────────── */}
        <section className="mb-20" data-reveal>
          <Card className="p-8">
            <h2 className="text-xl font-bold text-foreground mb-3">MECE the platform vs. the MECE principle</h2>
            <div className="grid gap-6 md:grid-cols-2">
              <div>
                <p className="text-sm font-semibold uppercase tracking-wider text-primary mb-2">The principle</p>
                <p className="text-body leading-relaxed text-foreground/80">
                  MECE — Mutually Exclusive, Collectively Exhaustive — is a problem-solving idea popularised by McKinsey
                  alumna Barbara Minto. It means breaking a problem into buckets with no overlaps and no gaps.
                </p>
              </div>
              <div>
                <p className="text-sm font-semibold uppercase tracking-wider text-primary mb-2">This platform</p>
                <p className="text-body leading-relaxed text-foreground/80">
                  MECE (mece.in) is a product, not a concept: an online place where Indian MBA/PGDM students read a free
                  casebook, practise cases and guesstimates, get rubric-scored, and rank nationally. Named after the
                  principle; distinct from it.
                </p>
              </div>
            </div>
          </Card>
        </section>

        {/* ── What you get ───────────────────────────────────────────── */}
        <section className="mb-20" data-reveal>
          <div className="text-center max-w-2xl mx-auto mb-12">
            <h2 className="text-3xl font-bold text-foreground">What you actually get</h2>
            <p className="mt-3 text-lg text-muted-foreground">
              Everything in one place — learn, practise, get scored, and see where you stand.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {WHAT_YOU_GET.map(({ icon: Icon, title, body }) => (
              <Card key={title} className="p-7 flex flex-col items-start text-left transition-shadow hover:shadow-md">
                <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center mb-5">
                  <Icon className="h-6 w-6 text-primary" />
                </div>
                <h3 className="text-lg font-bold text-foreground mb-2">{title}</h3>
                <p className="text-body text-muted-foreground leading-relaxed">{body}</p>
              </Card>
            ))}
          </div>
        </section>

        {/* ── The problem we solve (navy block) ──────────────────────── */}
        <section className="mb-20" data-reveal>
          <div className="bg-navy rounded-3xl p-10 md:p-16 text-white shadow-lg relative overflow-hidden">
            <div className="relative z-10 max-w-4xl mx-auto">
              <h2 className="text-3xl font-bold mb-6 text-white">The problem we solve</h2>
              <p className="text-lg leading-relaxed text-navy-foreground/80 mb-8">
                Every placement season runs on the same quiet unfairness. Two equally hardworking students walk into the same shortlist — one had seniors who ran drills with them all term, the other had a WhatsApp group and hope. Peer mocks go easy on you. Bootcamps charge a month's stipend. And nobody can tell you, consistently, whether you are actually getting better. The stakes are a career; the feedback is a lottery.
              </p>
              <div className="bg-white/10 p-8 rounded-xl border border-white/20">
                <p className="text-lg leading-relaxed text-white">
                  <strong className="text-primary-foreground font-semibold">The MECE way:</strong> replace subjectivity
                  with a consistent rubric. Practise any hour, get the same rigorous 100-point feedback every time, and
                  track genuine improvement instead of wondering whether your structure was good enough.
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* ── How scoring works (teaser → methodology) ───────────────── */}
        <section className="mb-20" data-reveal>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
            <div>
              <h2 className="text-3xl font-bold text-foreground mb-4">How the scoring works</h2>
              <p className="text-body leading-relaxed text-foreground/80 mb-5">
                Every answer is graded on a transparent, 100-point rubric across six dimensions — the same rubric for
                everyone, every time — so your score is comparable across sessions and against your peers. An arithmetic
                backstop independently checks the numbers in guesstimates, so a confident-sounding wrong answer cannot
                quietly score well.
              </p>
              <ul className="space-y-2.5 mb-6">
                {['Structure (25)', 'Quantitative (20)', 'Synthesis (20)', 'Business Judgment (15)', 'Creativity (10)', 'Professional Tone (10)'].map((d) => (
                  <li key={d} className="flex items-center gap-2.5 text-body text-foreground">
                    <CheckCircle2 className="h-4 w-4 text-primary flex-shrink-0" />
                    {d}
                  </li>
                ))}
              </ul>
              <Link href="/methodology" className="inline-flex">
                <button className="btn-ghost">
                  Read the full methodology <ArrowRight className="h-4 w-4" />
                </button>
              </Link>
            </div>
            <Card className="p-8 flex flex-col items-center justify-center text-center">
              <Layers className="h-14 w-14 text-primary mb-5" />
              <h3 className="text-lg font-bold text-foreground mb-1">Mutually Exclusive</h3>
              <p className="text-body text-muted-foreground mb-6">No overlaps. Every point is distinct.</p>
              <h3 className="text-lg font-bold text-foreground mb-1">Collectively Exhaustive</h3>
              <p className="text-body text-muted-foreground">No gaps. Every possibility is covered.</p>
            </Card>
          </div>
        </section>

        {/* ── Who builds MECE ────────────────────────────────────────── */}
        <section className="mb-20" data-reveal>
          <div className="text-center max-w-2xl mx-auto mb-10">
            <h2 className="text-3xl font-bold text-foreground">Who builds MECE</h2>
          </div>
          <Card className="p-8 md:p-12 max-w-3xl mx-auto">
            <p className="text-body leading-relaxed text-foreground/80 mb-5">
              MECE is built and run by a small, independent team that went through the Indian
              B-school placement circuit — the shortlists, the case mocks, the guesstimate
              drills — and came out convinced that preparation shouldn&apos;t depend on how
              lucky you got with seniors, schedules, or feedback.
            </p>
            <p className="text-body leading-relaxed text-foreground/80 mb-5">
              We keep this page deliberately free of faces and bios. Not because there is
              anything to hide, but because names are the wrong proof. In a case interview,
              nobody cares who taught you — they care whether your structure holds. We hold
              ourselves to the same standard we score you on.
            </p>
            <p className="text-body leading-relaxed text-foreground/80 mb-8">
              So instead of credentials, here is what we stake the platform on — all of it
              public, all of it checkable:
            </p>
            <ul className="space-y-3">
              {[
                'A fully public methodology — the exact 100-point, six-dimension rubric is documented on the methodology page for anyone to read.',
                'The same rubric for every student, every submission, every time. No moods, no favourites, no easy graders.',
                'An arithmetic backstop that independently re-checks the math in every guesstimate, so confident nonsense cannot score well.',
                'A free, openly readable casebook — 145+ pages of frameworks, worked cases, and guesstimates, no account required.',
              ].map((point) => (
                <li key={point} className="flex items-start gap-2.5 text-body text-foreground leading-relaxed">
                  <CheckCircle2 className="h-4 w-4 text-primary flex-shrink-0 mt-1" />
                  {point}
                </li>
              ))}
            </ul>
            <p className="text-body leading-relaxed text-foreground/80 mt-8">
              Judge us the way an interviewer judges you — on the work, not the signalling.
            </p>
          </Card>
        </section>

        {/* ── FAQ ────────────────────────────────────────────────────── */}
        <section className="mb-20 max-w-3xl mx-auto" data-reveal>
          <div className="text-center mb-10">
            <div className="inline-flex items-center gap-1.5 text-sm font-semibold uppercase tracking-wider text-primary mb-3">
              <HelpCircle className="h-4 w-4" /> FAQ
            </div>
            <h2 className="text-3xl font-bold text-foreground">Common questions</h2>
          </div>
          <div className="space-y-3">
            {ABOUT_FAQS.map((faq) => (
              <details key={faq.question} className="bg-card border border-border rounded-xl p-5 group">
                <summary className="flex items-center justify-between gap-4 cursor-pointer list-none [&::-webkit-details-marker]:hidden text-base font-semibold text-foreground">
                  {faq.question}
                  <ChevronRight className="h-4 w-4 flex-shrink-0 text-muted-foreground transition-transform group-open:rotate-90" />
                </summary>
                <p className="mt-3 text-body text-muted-foreground leading-relaxed">{faq.answer}</p>
              </details>
            ))}
          </div>
        </section>

        {/* ── Independence note ──────────────────────────────────────── */}
        <p className="max-w-3xl mx-auto text-center text-small text-muted-foreground mb-16" data-reveal>
          MECE is an independent educational tool. It is not affiliated with, endorsed by, or connected to McKinsey, BCG,
          Bain, or any firm or business school referenced on the platform. Trademarks belong to their respective owners.
        </p>

        {/* ── CTA ────────────────────────────────────────────────────── */}
        <section className="text-center bg-card rounded-3xl p-14 border border-border shadow-md" data-reveal>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">Ready to elevate your prep?</h2>
          <p className="text-lg text-muted-foreground mb-10 max-w-2xl mx-auto">
            Your placement season starts now. Start with the free casebook, then practise and see where you rank.
          </p>
          <Link href="/signup">
            <button className="btn-primary text-lg px-10 py-4 shadow-md hover:shadow-lg transition-all">
              Start practising free
            </button>
          </Link>
        </section>
      </main>
      <Footer />
    </div>
  );
}
