import { createClient } from '@/lib/supabase/server';
import AppNav from '@/components/app-nav';
import { UserProvider } from '@/components/user-context';
import Footer from '@/components/footer';
import type { UserRow } from '@/lib/types';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Privacy policy',
  description: 'How MECE collects, uses, and protects your data.',
  alternates: { canonical: '/privacy' },
};

export default async function PrivacyPage() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  
  let userRow: UserRow | null = null;
  if (user) {
    const { data } = await supabase.from('users').select('*').eq('id', user.id).maybeSingle();
    userRow = data as UserRow | null;
  }

  return (
    <div className="min-h-screen bg-muted flex flex-col">
      <UserProvider initialUser={userRow}>
        <AppNav />
      </UserProvider>
      <main className="container max-w-4xl py-16 flex-grow">
        <div className="mb-12">
          <p className="text-base font-semibold uppercase tracking-wider text-primary mb-2">Legal</p>
          <h1 className="text-4xl font-extrabold tracking-tight text-foreground">
            Privacy Policy
          </h1>
          <p className="mt-4 text-muted-foreground">Last Updated: June 2026</p>
        </div>

        <div className="prose prose-slate max-w-none text-foreground/80 space-y-8">
          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">1. Introduction</h2>
            <p className="leading-relaxed">
              Welcome to MECE ("we," "our," or "us"). We are committed to protecting your personal data and respecting your privacy. This Privacy Policy governs your use of the MECE.in website and the associated technology-driven placement-interview preparation services, with automated rubric evaluation (the "Platform").
              By using our Platform, you agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">2. Information We Collect</h2>
            <p className="leading-relaxed mb-4">
              We collect several different types of information for various purposes to provide and improve our Service to you.
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong>Personal Data:</strong> Email address, first name, last name, phone number, institutional affiliation (MBA/PGDM college), and graduation year.</li>
              <li><strong>Usage Data:</strong> Information on how the Platform is accessed and used, including your IP address, browser type, pages visited, time spent, and diagnostic data.</li>
              <li><strong>User-Generated Content:</strong> Case responses, guesstimate calculations, group discussion briefs, and performance scores generated by our AI engine.</li>
              <li><strong>Payment Information:</strong> When you upgrade to Lite or Pro tiers, billing data is processed securely through Razorpay. We do not store full credit card details on our servers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">3. Use of Data and AI Processing</h2>
            <p className="leading-relaxed mb-4">
              Your data is utilized to:
            </p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>Provide, operate, and maintain our Platform.</li>
              <li>Generate personalized 100-point rubric scores and actionable feedback via our AI engine.</li>
              <li>Populate the cross-India live leaderboard (your name/school may be visible to other authenticated users depending on your privacy settings).</li>
              <li>Monitor usage patterns to improve case materials and algorithmic accuracy.</li>
              <li>Process payments and manage your subscription.</li>
            </ul>
            <p className="leading-relaxed">
              <strong>Third-Party AI Processing:</strong> To evaluate your submissions, your case responses are securely transmitted to our external AI partners (e.g., OpenAI). These transmissions are processed transiently via API and are subject to strict data processing agreements ensuring your responses are not used to train public foundational models.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">4. Data Storage, Retention, and Security</h2>
            <p className="leading-relaxed">
              We store your data securely using Supabase. We retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We employ industry-standard security measures, including encryption in transit and at rest, to protect your data. However, no method of transmission over the Internet is 100% secure, and we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">5. Disclosure of Data</h2>
            <p className="leading-relaxed mb-4">
              We may disclose your Personal Data in the good faith belief that such action is necessary to:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Comply with a legal obligation or lawful government request.</li>
              <li>Protect and defend the rights or property of MECE.</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Platform.</li>
              <li>Protect the personal safety of users of the Service or the public.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">6. Your Data Rights</h2>
            <p className="leading-relaxed">
              Depending on your jurisdiction (including compliance with applicable Indian data protection guidelines), you may have the right to access, update, delete, or restrict the processing of your personal data. You can manage your profile details from the Dashboard. For full data deletion requests, please contact our support team.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">7. Changes to This Privacy Policy</h2>
            <p className="leading-relaxed">
              We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">8. Contact Us</h2>
            <p className="leading-relaxed">
              If you have any questions about this Privacy Policy, the data we hold on you, or you would like to exercise one of your data protection rights, please do not hesitate to contact us at: <a href="mailto:team@mece.in" className="text-primary hover:underline">team@mece.in</a>.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
