#!/usr/bin/env node
/*
 * .brain/sync.mjs — regenerate STATE.md from git + LEDGER.md
 *
 * Run by Antigravity (the worker) after every merge to main, or wire it as a
 * git hook:  .git/hooks/post-merge  ->  node .brain/sync.mjs
 *
 * Dependency-free. Works on Windows (git-bash / PowerShell) and *nix.
 * It is deterministic: brains never hand-edit STATE.md, this rebuilds it.
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const git = (cmd) => {
  try { return execSync(`git ${cmd}`, { cwd: HERE, encoding: "utf8" }).trim(); }
  catch { return ""; }
};

const branch   = git("rev-parse --abbrev-ref HEAD") || "main";
const commits  = git('log -5 --pretty=format:"- %h %s (%an, %ad)" --date=short')
                  .split("\n").filter(Boolean);
const featBr   = git("branch -r --no-merged main")
                  .split("\n").map(s => s.trim()).filter(b => b && b.includes("feat/"));

// Pull the per-feature mirror straight out of LEDGER.md so the two never disagree.
let ledgerRows = "(LEDGER.md table not found)";
const ledgerPath = join(HERE, "LEDGER.md");
if (existsSync(ledgerPath)) {
  const lines = readFileSync(ledgerPath, "utf8").split("\n");
  const header = lines.findIndex(l => l.startsWith("| Feature"));
  if (header !== -1) {
    const rows = [];
    for (let i = header; i < lines.length; i++) {
      if (lines[i].startsWith("|")) rows.push(lines[i]); else if (rows.length) break;
    }
    // keep only Feature | Owner | Branch | Status (cols 1-4) for the compact mirror
    ledgerRows = rows.map(r => {
      const c = r.split("|").map(s => s.trim());
      return `| ${c[1]} | ${c[2]} | ${c[3]} | ${c[4]} |`;
    }).join("\n");
  }
}

// First entry header in CHANGELOG = "last landed"
let lastLanded = "(none)";
const clPath = join(HERE, "CHANGELOG.md");
if (existsSync(clPath)) {
  const m = readFileSync(clPath, "utf8").match(/^## .+$/m);
  if (m) lastLanded = m[0].replace(/^##\s*/, "");
}

const now = new Date().toISOString().slice(0, 16).replace("T", " ");

const out = `<!-- AUTO-GENERATED by .brain/sync.mjs — do not hand-edit. Last run: ${now} -->
# STATE — what is true right now

**Repo:** mece (frontend: Next.js 14 / Supabase / Razorpay) + backend (FastAPI)
**Branch:** ${branch}
**Last landed:** ${lastLanded}
**Last sync:** ${now} UTC

## Last 5 commits
${commits.length ? commits.join("\n") : "- (no commits found)"}

## Open feature branches (not merged into main)
${featBr.length ? featBr.map(b => `- ${b}`).join("\n") : "- (none)"}

## Per-feature status (mirror of LEDGER.md)
${ledgerRows}

## Reminder for every brain
Read the top of CHANGELOG.md next. If a \`BREAKING\` entry lists your feature in
\`affects:\`, re-read the changed CONTRACTS.md surface before writing anything.
`;

writeFileSync(join(HERE, "STATE.md"), out);
console.log("STATE.md regenerated:", now);
