#!/usr/bin/env node
/**
 * Generates supabase/seed-us-market.sql from lib/us-market/*.ts.
 *
 *   node scripts/gen-us-seed.mjs
 *
 * The TypeScript bank is the single source of truth; this script transpiles it
 * with the repo's own tsc, validates it, and writes an idempotent upsert keyed
 * on cases.code. Never hand-edit the generated SQL.
 */
import { execSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = mkdtempSync(join(tmpdir(), 'us-seed-'));
execSync(
  `npx tsc --ignoreConfig lib/us-market/index.ts --outDir ${out} --module commonjs --target es2020 --skipLibCheck --esModuleInterop`,
  { cwd: root, stdio: 'inherit' },
);
const require = createRequire(import.meta.url);
const bank = require(join(out, 'index.js'));
rmSync(out, { recursive: true, force: true });

const { US_CASES, US_GUESSTIMATES, usCaseContent, usGuesstimateContent, pointsFor } = bank;

// ── Validation: fail loudly rather than seed a broken bank ─────────────────
const VALID_TYPES = new Set(['profitability', 'market entry', 'growth', 'pricing', 'm&a', 'operations',
  'cost reduction', 'go to market', 'competitive strategy']);
const VALID_DIFF = new Set(['easy', 'medium', 'hard']);
const codes = new Set();
const slugs = new Set();
function check(cond, msg) { if (!cond) { console.error('INVALID:', msg); process.exit(1); } }
check(US_CASES.length === 50, `expected 50 cases, got ${US_CASES.length}`);
check(US_GUESSTIMATES.length === 50, `expected 50 guesstimates, got ${US_GUESSTIMATES.length}`);
for (const c of US_CASES) {
  check(/^US-C-\d{2}$/.test(c.code), `bad case code ${c.code}`);
  check(VALID_TYPES.has(c.type), `${c.code}: bad type ${c.type}`);
  check(VALID_DIFF.has(c.difficulty), `${c.code}: bad difficulty`);
  check(c.facts.length >= 2 && c.asks.length >= 2, `${c.code}: needs facts and asks`);
  check(c.solution.length > 200 && c.hint.length > 20, `${c.code}: thin solution/hint`);
}
for (const g of US_GUESSTIMATES) {
  check(/^US-G-\d{2}$/.test(g.code), `bad guesstimate code ${g.code}`);
  check(VALID_DIFF.has(g.difficulty), `${g.code}: bad difficulty`);
  check(g.solution.length > 150 && g.hint.length > 20, `${g.code}: thin solution/hint`);
}
for (const x of [...US_CASES, ...US_GUESSTIMATES]) {
  check(!codes.has(x.code), `duplicate code ${x.code}`); codes.add(x.code);
  check(!slugs.has(x.slug), `duplicate slug ${x.slug}`); slugs.add(x.slug);
  check(/^[a-z0-9-]+$/.test(x.slug), `bad slug ${x.slug}`);
  // House rules: no rupee/lakh/crore in the US bank, no em/en dashes-as-hyphens issues are fine.
  const all = JSON.stringify(x);
  check(!/[₹]|\blakh\b|\bcrore\b|\bRs\b/.test(all), `${x.code}: India currency terms in the US bank`);
}

// ── SQL ─────────────────────────────────────────────────────────────────────
const TAG = '$us$';
function lit(s) {
  if (s === null || s === undefined) return 'null';
  const str = String(s);
  check(!str.includes(TAG), `text contains the quote tag ${TAG}`);
  return `${TAG}${str}${TAG}`;
}
function json(o) { return `${lit(JSON.stringify(o))}::jsonb`; }

const rows = [];
for (const c of US_CASES) {
  rows.push(`  (${[
    lit(c.code), lit(c.title), lit(c.type), lit(c.difficulty), lit(usCaseContent(c)),
    lit(c.hint), lit(c.solution), 'true', 'null', lit(c.cluster),
    json({ firm: c.firm, round: c.difficulty === 'hard' ? 'final round' : 'first round', est_minutes: c.minutes,
      points_reward: pointsFor(c.difficulty, false), source: 'us-bank', format: c.format, industry: c.industry }),
    `'US'`,
  ].join(', ')})`);
}
for (const g of US_GUESSTIMATES) {
  rows.push(`  (${[
    lit(g.code), lit(g.title), `'guesstimate'`, lit(g.difficulty), lit(usGuesstimateContent(g)),
    lit(g.hint), lit(g.solution), 'true', 'null', `'size'`,
    json({ firm: g.firm, round: 'first round', est_minutes: g.minutes,
      points_reward: pointsFor(g.difficulty, true), source: 'us-bank' }),
    `'US'`,
  ].join(', ')})`);
}

const sql = `-- =====================================================================
-- US case bank — 50 cases + 50 guesstimates (international market)
-- GENERATED by scripts/gen-us-seed.mjs from lib/us-market/*.ts.
-- DO NOT EDIT BY HAND: edit the TypeScript bank and re-run the script.
--
-- REQUIRES migration 0070_international_markets.sql (cases.market) and
-- 0017_cases_type_expand.sql (the practice-domain case types).
--
-- Idempotent: upsert keyed on cases.code. Re-running refreshes the text of
-- the US rows only — the WHERE clause refuses to touch any row that is not
-- already a US-bank row, so an India case can never be overwritten.
-- Every scenario is invented for practice; company names are fictional.
-- =====================================================================

insert into public.cases
  (code, title, type, difficulty, content, hint, solution, is_active, skill_node, skill_cluster, interview_meta, market)
values
${rows.join(',\n')}
on conflict (code) do update set
  title          = excluded.title,
  type           = excluded.type,
  difficulty     = excluded.difficulty,
  content        = excluded.content,
  hint           = excluded.hint,
  solution       = excluded.solution,
  skill_cluster  = excluded.skill_cluster,
  interview_meta = excluded.interview_meta
where public.cases.market = 'US';

-- Bootstrap: give the US market a daily pair immediately, so international
-- users see a daily case and guesstimate before the first US cron run. Only
-- fires when the US schedule is completely empty (a no-op on every re-run).
insert into public.market_daily_schedule (market, scheduled_date, case_id, guesstimate_id, source)
select 'US', (now() at time zone 'America/New_York')::date,
       (select id from public.cases where code = 'US-C-05' and market = 'US'),
       (select id from public.cases where code = 'US-G-01' and market = 'US'),
       'bank'
where not exists (select 1 from public.market_daily_schedule where market = 'US');

-- VERIFY: expect 50 guesstimates and 50 cases, all market 'US'.
--   select type = 'guesstimate' as is_guesstimate, count(*)
--     from public.cases where code like 'US-%' and market = 'US' group by 1;
`;

writeFileSync(join(root, 'supabase', 'seed-us-market.sql'), sql);
console.log(`Wrote supabase/seed-us-market.sql: ${US_CASES.length} cases + ${US_GUESSTIMATES.length} guesstimates.`);
